"""Machine-generated by recast.transform.jax -- JAX backend (EXPERIMENTAL).

Loop-faithful lax emission from mlleafheatcapacitymod_numpy.py. Cannot pass a bit-exact
gate: XLA lowers transcendentals to its own implementations and fuses
multiply-add. The gate is the ULP tier against the validated numpy module --
see recast.verify.tolerance. Do not hand-edit; fix the backend instead.
B-block provenance lives in the numpy module.
"""

import jax
import jax.numpy as jnp
import numpy as np
from jax import lax

from mlleafheatcapacitymod_jax_runtime import *  # noqa: F401,F403  (enables x64, _f_* jnp shims)
from mlleafheatcapacitymod_constants import *  # noqa: F401,F403
import mlleafheatcapacitymod_numpy as _host

# Which device this module will run on. A ULP bound between a GPU and a CPU is
# a different claim from one between two CPUs, and the gate records what the
# module says rather than importing an accelerator to find out.
_DEVICE = str(jax.devices()[0])

import clm_varcon_numpy as _clm_varcon
import mlcanopyfluxestype_numpy as _mlca
import mlclm_varcon_numpy as _mlc
import patchtype_numpy as _patchtype
import pftconmod_numpy as _pftconmod

_SIGNATURES = {'leafheatcapacity': {'kind': 'subroutine', 'args': [{'name': 'num_filter', 'dtype': 'int32', 'intent': 'IN', 'optional': False}, {'name': 'filter', 'dtype': 'int32', 'intent': 'IN', 'optional': False, 'dims': [{'lb': '1', 'ub': None}]}, {'name': 'mlcanopy_inst', 'dtype': 'UNKNOWN(TYPE(MLCANOPY_TYPE))', 'intent': 'INOUT', 'optional': False}], 'result': None, 'result_dtype': None}}
_SIGNATURES.update({'leafheatcapacity_flat': {'kind': 'subroutine', 'args': [{'name': 'num_filter', 'dtype': 'int32', 'intent': 'IN', 'optional': False, 'dims': None}, {'name': 'filter', 'dtype': 'int32', 'intent': 'IN', 'optional': False, 'dims': [{'lb': '1', 'ub': 'num_filter'}]}, {'name': 'np_', 'dtype': 'int32', 'intent': 'IN', 'optional': False, 'dims': None}, {'name': 'mlcanopy_inst__cpleaf_profile', 'dtype': 'float64', 'intent': 'INOUT', 'optional': False, 'dims': [{'lb': '1', 'ub': 'np_'}, {'lb': '1', 'ub': '100'}]}, {'name': 'mlcanopy_inst__dpai_profile', 'dtype': 'float64', 'intent': 'IN', 'optional': False, 'dims': [{'lb': '1', 'ub': 'np_'}, {'lb': '1', 'ub': '100'}]}, {'name': 'mlcanopy_inst__ncan_canopy', 'dtype': 'int32', 'intent': 'IN', 'optional': False, 'dims': [{'lb': '1', 'ub': 'np_'}]}, {'name': 'patch__itype', 'dtype': 'int32', 'intent': 'IN', 'optional': False, 'dims': [{'lb': '1', 'ub': 'np_'}]}, {'name': 'pftcon__slatop', 'dtype': 'float64', 'intent': 'IN', 'optional': False, 'dims': [{'lb': '1', 'ub': '79'}]}, {'name': 'clm_varcon__cpliq', 'dtype': 'float64', 'intent': 'IN', 'optional': False, 'dims': None}, {'name': 'mlclm_varcon__cpbio', 'dtype': 'float64', 'intent': 'IN', 'optional': False, 'dims': None}, {'name': 'mlclm_varcon__fcarbon', 'dtype': 'float64', 'intent': 'IN', 'optional': False, 'dims': None}, {'name': 'mlclm_varcon__fwater', 'dtype': 'float64', 'intent': 'IN', 'optional': False, 'dims': None}], 'result': None, 'result_dtype': None}})


def _leafheatcapacity_flat_k_impl(num_filter, filter, np_, mlcanopy_inst__cpleaf_profile, mlcanopy_inst__dpai_profile, mlcanopy_inst__ncan_canopy, patch__itype, pftcon__slatop, clm_varcon__cpliq, mlclm_varcon__cpbio, mlclm_varcon__fcarbon, mlclm_varcon__fwater):
    """L24-L85 subroutine (machine-translated)."""
    fp = jnp.int32(0)
    p = jnp.int32(0)
    ic = jnp.int32(0)
    lma = jnp.float64(0.0)
    dry_weight = jnp.float64(0.0)
    fresh_weight = jnp.float64(0.0)
    leaf_water = jnp.float64(0.0)

    def _body_5(fp, _c):
        p, lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = _c

        def _true_4(_c):
            p, lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = _c
            p = filter[fp - 1]

            def _body_3(ic, _c):
                lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = _c

                def _true_2(_c):
                    lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = _c

                    def _true_1(_c):
                        lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = _c
                        lma = 1.0 / pftcon__slatop[patch__itype[p - 1] - 0] * F_0P001
                        dry_weight = lma / mlclm_varcon__fcarbon
                        fresh_weight = dry_weight / (1.0 - mlclm_varcon__fwater)
                        leaf_water = mlclm_varcon__fwater * fresh_weight
                        mlcanopy_inst__cpleaf_profile = mlcanopy_inst__cpleaf_profile.at[p - 1, ic - 1].set(mlclm_varcon__cpbio * dry_weight + clm_varcon__cpliq * leaf_water)
                        return (lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile)

                    def _false_1(_c):
                        lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = _c
                        mlcanopy_inst__cpleaf_profile = mlcanopy_inst__cpleaf_profile.at[p - 1, ic - 1].set(0.0)
                        return (lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile)
                    lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = lax.cond(mlcanopy_inst__dpai_profile[p - 1, ic - 1] > 0.0, _true_1, _false_1, (lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile))
                    return (lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile)

                def _false_2(_c):
                    lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = _c
                    return (lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile)
                lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = lax.cond(ic < mlcanopy_inst__ncan_canopy[p - 1] + 1, _true_2, _false_2, (lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile))
                return (lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile)
            lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = lax.fori_loop(1, mlcanopy_inst__dpai_profile.shape[1] + 1, _body_3, (lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile))
            return (p, lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile)

        def _false_4(_c):
            p, lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = _c
            return (p, lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile)
        p, lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = lax.cond(fp < num_filter + 1, _true_4, _false_4, (p, lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile))
        return (p, lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile)
    p, lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile = lax.fori_loop(1, filter.shape[0] + 1, _body_5, (p, lma, dry_weight, fresh_weight, leaf_water, mlcanopy_inst__cpleaf_profile))
    return mlcanopy_inst__cpleaf_profile


_leafheatcapacity_flat_k = jax.jit(_leafheatcapacity_flat_k_impl, static_argnums=(0, 2, 8, 9, 10, 11))


def leafheatcapacity_flat(num_filter, filter, np_, mlcanopy_inst__cpleaf_profile, mlcanopy_inst__dpai_profile, mlcanopy_inst__ncan_canopy, patch__itype, pftcon__slatop, clm_varcon__cpliq, mlclm_varcon__cpbio, mlclm_varcon__fcarbon, mlclm_varcon__fwater):
    """Host wrapper: state read from the validated numpy module."""
    import patchtype_numpy as _patchtype
    if not hasattr(getattr(_patchtype, 'patch', None), '__dict__'):
        _patchtype.patch = _host._Record()
    _patchtype.patch.itype = jnp.asarray(patch__itype)
    import pftconmod_numpy as _pftconmod
    if not hasattr(getattr(_pftconmod, 'pftcon', None), '__dict__'):
        _pftconmod.pftcon = _host._Record()
    _pftconmod.pftcon.slatop = jnp.asarray(pftcon__slatop)
    import clm_varcon_numpy as _clm_varcon
    _clm_varcon.cpliq = jnp.asarray(clm_varcon__cpliq)
    import mlclm_varcon_numpy as _mlclm_varcon
    _mlclm_varcon.cpbio = jnp.asarray(mlclm_varcon__cpbio)
    import mlclm_varcon_numpy as _mlclm_varcon
    _mlclm_varcon.fcarbon = jnp.asarray(mlclm_varcon__fcarbon)
    import mlclm_varcon_numpy as _mlclm_varcon
    _mlclm_varcon.fwater = jnp.asarray(mlclm_varcon__fwater)
    return _leafheatcapacity_flat_k(num_filter, filter, np_, mlcanopy_inst__cpleaf_profile, mlcanopy_inst__dpai_profile, mlcanopy_inst__ncan_canopy, patch__itype, pftcon__slatop, clm_varcon__cpliq, mlclm_varcon__cpbio, mlclm_varcon__fcarbon, mlclm_varcon__fwater)


leafheatcapacity = _host.leafheatcapacity


_JAX_KERNELS = ['leafheatcapacity_flat']
