"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlpftconmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

MXPFT = 78  # clm_varpar.f90:23
