"""Machine-generated by recast.transform.jax -- JAX backend (EXPERIMENTAL).

Loop-faithful lax emission from mlcanopyfluxestype_numpy.py. Cannot pass a bit-exact
gate: XLA lowers transcendentals to its own implementations and fuses
multiply-add. The gate is the ULP tier against the validated numpy module --
see recast.verify.tolerance. Do not hand-edit; fix the backend instead.
B-block provenance lives in the numpy module.
"""

import jax
import jax.numpy as jnp
import numpy as np
from jax import lax

from mlcanopyfluxestype_jax_runtime import *  # noqa: F401,F403  (enables x64, _f_* jnp shims)
from mlcanopyfluxestype_constants import *  # noqa: F401,F403
import mlcanopyfluxestype_numpy as _host

# Which device this module will run on. A ULP bound between a GPU and a CPU is
# a different claim from one between two CPUs, and the gate records what the
# module says rather than importing an accelerator to find out.
_DEVICE = str(jax.devices()[0])

from mlcanopyfluxestype_use_constants import *  # noqa: F401,F403
import clm_varpar_numpy as _clm_varpar
import mlclm_varctl_numpy as _mlc

_SIGNATURES = {'init': {'kind': 'subroutine', 'args': [{'name': 'this', 'dtype': 'UNKNOWN(CLASS(MLCANOPY_TYPE))', 'intent': 'UNKNOWN', 'optional': False}, {'name': 'bounds', 'dtype': 'UNKNOWN(TYPE(BOUNDS_TYPE))', 'intent': 'IN', 'optional': False}], 'result': None, 'result_dtype': None}, 'initallocate': {'kind': 'subroutine', 'args': [{'name': 'this', 'dtype': 'UNKNOWN(CLASS(MLCANOPY_TYPE))', 'intent': 'UNKNOWN', 'optional': False}, {'name': 'bounds', 'dtype': 'UNKNOWN(TYPE(BOUNDS_TYPE))', 'intent': 'IN', 'optional': False}], 'result': None, 'result_dtype': None}, 'inithistory': {'kind': 'subroutine', 'args': [{'name': 'this', 'dtype': 'UNKNOWN(CLASS(MLCANOPY_TYPE))', 'intent': 'UNKNOWN', 'optional': False}, {'name': 'bounds', 'dtype': 'UNKNOWN(TYPE(BOUNDS_TYPE))', 'intent': 'IN', 'optional': False}], 'result': None, 'result_dtype': None}, 'initcold': {'kind': 'subroutine', 'args': [{'name': 'this', 'dtype': 'UNKNOWN(CLASS(MLCANOPY_TYPE))', 'intent': 'UNKNOWN', 'optional': False}, {'name': 'bounds', 'dtype': 'UNKNOWN(TYPE(BOUNDS_TYPE))', 'intent': 'IN', 'optional': False}], 'result': None, 'result_dtype': None}, 'restart': {'kind': 'subroutine', 'args': [{'name': 'this', 'dtype': 'UNKNOWN(CLASS(MLCANOPY_TYPE))', 'intent': 'UNKNOWN', 'optional': False}, {'name': 'bounds', 'dtype': 'UNKNOWN(TYPE(BOUNDS_TYPE))', 'intent': 'IN', 'optional': False}, {'name': 'ncid', 'dtype': 'UNKNOWN(TYPE(FILE_DESC_T))', 'intent': 'INOUT', 'optional': False}, {'name': 'flag', 'dtype': 'str', 'intent': 'IN', 'optional': False}], 'result': None, 'result_dtype': None}}


init = _host.init


initallocate = _host.initallocate


inithistory = _host.inithistory


initcold = _host.initcold


restart = _host.restart


_JAX_KERNELS = []
