"""Machine-generated by recast — DO NOT EDIT."""
# source: pftconMod.f90 (module pftconmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P001 = np.float64('0.001')  # initread:238; initread:241
F_0P008 = np.float64('0.008')  # initread:262
F_0P01 = np.float64('0.01')  # initread:188; initread:190; initread:192
F_0P010 = np.float64('0.010')  # initread:261
F_0P012 = np.float64('0.012')  # initread:264; initread:265; initread:269
F_0P024 = np.float64('0.024')  # initread:263
F_0P030 = np.float64('0.030')  # initread:266; initread:267; initread:268; initread:270; initread:271; initread:272; initread:273; initread:274; initread:275; initread:276
F_0P04 = np.float64('0.04')  # initread:176; initread:298
F_0P05 = np.float64('0.05')  # initread:226
F_0P06 = np.float64('0.06')  # initread:289
F_0P07 = np.float64('0.07')  # initread:200; initread:202
F_0P10 = np.float64('0.10')  # initread:189; initread:201; initread:203; initread:228; initread:230
F_0P11 = np.float64('0.11')  # initread:204
F_0P12 = np.float64('0.12')  # initread:239
F_0P16 = np.float64('0.16')  # initread:216
F_0P21 = np.float64('0.21')  # initread:294
F_0P25 = np.float64('0.25')  # initread:191; initread:193; initread:229; initread:231; initread:242
F_0P30 = np.float64('0.30')  # initread:194
F_0P31 = np.float64('0.31')  # initread:217
F_0P34 = np.float64('0.34')  # initread:232
F_0P35 = np.float64('0.35')  # initread:206; initread:208; initread:210
F_0P39 = np.float64('0.39')  # initread:219
F_0P42 = np.float64('0.42')  # initread:292
F_0P43 = np.float64('0.43')  # initread:301
F_0P45 = np.float64('0.45')  # initread:207; initread:209
F_0P49 = np.float64('0.49')  # initread:295
F_0P53 = np.float64('0.53')  # initread:220; initread:286
F_0P914 = np.float64('0.914')  # initread:255
F_0P943 = np.float64('0.943')  # initread:248; initread:253; initread:256
F_0P964 = np.float64('0.964')  # initread:254
F_0P966 = np.float64('0.966')  # initread:250; initread:252
F_0P976 = np.float64('0.976')  # initread:247
F_0P993 = np.float64('0.993')  # initread:249; initread:251
F_999P = np.float64('999.')  # initread:175; initread:180; initread:187; initread:198; initread:214; initread:224; initread:236; initread:246; initread:260
I_10 = np.int32(10)  # initread:193; initread:203; initread:209; initread:231; initread:254; initread:270
I_11 = np.int32(11)  # initread:193; initread:203; initread:209; initread:216; initread:219; initread:231; initread:238; initread:241; initread:255; initread:271
I_12 = np.int32(12)  # initread:194; initread:204; initread:210; initread:217; initread:220; initread:232; initread:239; initread:242; initread:255; initread:272
I_13 = np.int32(13)  # initread:181; initread:256; initread:273
I_14 = np.int32(14)  # initread:182; initread:274
I_15 = np.int32(15)  # initread:183; initread:275
I_16 = np.int32(16)  # initread:176; initread:183; initread:194; initread:204; initread:210; initread:217; initread:220; initread:226; initread:232; initread:239; initread:242; initread:256; initread:276
I_3 = np.int32(3)  # initread:188; initread:200; initread:206; initread:228; initread:248; initread:263
I_4 = np.int32(4)  # initread:189; initread:201; initread:207; initread:229; initread:249; initread:264
I_5 = np.int32(5)  # initread:189; initread:250; initread:265
I_6 = np.int32(6)  # initread:190; initread:251; initread:266
I_7 = np.int32(7)  # initread:191; initread:252; initread:267; initread:286; initread:289; initread:292; initread:294; initread:295; initread:298; initread:301
I_8 = np.int32(8)  # initread:191; initread:201; initread:207; initread:229; initread:253; initread:268
I_9 = np.int32(9)  # initread:192; initread:202; initread:208; initread:230; initread:254; initread:269
