"""Machine-generated by recast — DO NOT EDIT."""
# source: histFileMod.f90 (module histfilemod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
