"""Machine-generated by recast — DO NOT EDIT."""
# source: decompMod.f90 (module decompmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
