"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module soilwatermovementmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

NLEVSOI = (-1)  # clm_varpar.f90:17
DENH2O = np.float64('1000.')  # clm_varcon.f90:25
