"""Machine-generated by recast — DO NOT EDIT."""
# source: MLLeafFluxesMod.f90 (module mlleaffluxesmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_1PEM03 = np.float64('1.e-03')  # leaffluxes:133
F_2P = np.float64('2.')  # leaffluxes:105; leaffluxes:118
