"""Machine-generated by recast.transform.jax -- JAX backend (EXPERIMENTAL).

Loop-faithful lax emission from mlwatervapormod_numpy.py. Cannot pass a bit-exact
gate: XLA lowers transcendentals to its own implementations and fuses
multiply-add. The gate is the ULP tier against the validated numpy module --
see recast.verify.tolerance. Do not hand-edit; fix the backend instead.
B-block provenance lives in the numpy module.
"""

import jax
import jax.numpy as jnp
import numpy as np
from jax import lax

from mlwatervapormod_jax_runtime import *  # noqa: F401,F403  (enables x64, _f_* jnp shims)
from mlwatervapormod_constants import *  # noqa: F401,F403
import mlwatervapormod_numpy as _host

# Which device this module will run on. A ULP bound between a GPU and a CPU is
# a different claim from one between two CPUs, and the gate records what the
# module says rather than importing an accelerator to find out.
_DEVICE = str(jax.devices()[0])

from mlwatervapormod_use_constants import *  # noqa: F401,F403
import clm_varcon_numpy as _clm_varcon
import mlclm_varcon_numpy as _mlc

_SIGNATURES = {'satvap': {'kind': 'subroutine', 'public': True, 'args': [{'name': 't', 'dtype': 'float64', 'intent': 'IN', 'optional': False}, {'name': 'es', 'dtype': 'float64', 'intent': 'OUT', 'optional': False}, {'name': 'desdt', 'dtype': 'float64', 'intent': 'OUT', 'optional': False}], 'result': None, 'result_dtype': None}, 'latvap': {'kind': 'function', 'public': True, 'args': [{'name': 't', 'dtype': 'float64', 'intent': 'IN', 'optional': False}], 'result': 'lambda', 'result_dtype': 'float64'}}


def _satvap_k_impl(t):
    """L25-L113 subroutine (machine-translated)."""
    es = jnp.float64(0.0)
    desdt = jnp.float64(0.0)
    a0 = np.float64('6.11213476')
    a1 = np.float64('0.444007856')
    a2 = np.float64('0.143064234E-01')
    a3 = np.float64('0.264461437E-03')
    a4 = np.float64('0.305903558E-05')
    a5 = np.float64('0.196237241E-07')
    a6 = np.float64('0.892344772E-10')
    a7 = np.float64('-0.373208410E-12')
    a8 = np.float64('0.209339997E-15')
    b0 = np.float64('0.444017302')
    b1 = np.float64('0.286064092E-01')
    b2 = np.float64('0.794683137E-03')
    b3 = np.float64('0.121211669E-04')
    b4 = np.float64('0.103354611E-06')
    b5 = np.float64('0.404125005E-09')
    b6 = np.float64('-0.788037859E-12')
    b7 = np.float64('-0.114596802E-13')
    b8 = np.float64('0.381294516E-16')
    c0 = np.float64('6.11123516')
    c1 = np.float64('0.503109514')
    c2 = np.float64('0.188369801E-01')
    c3 = np.float64('0.420547422E-03')
    c4 = np.float64('0.614396778E-05')
    c5 = np.float64('0.602780717E-07')
    c6 = np.float64('0.387940929E-09')
    c7 = np.float64('0.149436277E-11')
    c8 = np.float64('0.262655803E-14')
    d0 = np.float64('0.503277922')
    d1 = np.float64('0.377289173E-01')
    d2 = np.float64('0.126801703E-02')
    d3 = np.float64('0.249468427E-04')
    d4 = np.float64('0.313703411E-06')
    d5 = np.float64('0.257180651E-08')
    d6 = np.float64('0.133268878E-10')
    d7 = np.float64('0.394116744E-13')
    d8 = np.float64('0.498070196E-16')
    tc = jnp.float64(0.0)
    tc = t - TFRZ

    def _true_1(_c):
        tc, = _c
        tc = jnp.float64(F_100P0)
        return (tc,)

    def _false_1(_c):
        tc, = _c
        return (tc,)
    tc, = lax.cond(tc > F_100P0, _true_1, _false_1, (tc,))

    def _true_2(_c):
        tc, = _c
        tc = jnp.float64(-F_75P0)
        return (tc,)

    def _false_2(_c):
        tc, = _c
        return (tc,)
    tc, = lax.cond(tc < -F_75P0, _true_2, _false_2, (tc,))

    def _true_3(_c):
        es, desdt = _c
        es = a0 + tc * (a1 + tc * (a2 + tc * (a3 + tc * (a4 + tc * (a5 + tc * (a6 + tc * (a7 + tc * a8)))))))
        desdt = b0 + tc * (b1 + tc * (b2 + tc * (b3 + tc * (b4 + tc * (b5 + tc * (b6 + tc * (b7 + tc * b8)))))))
        return (es, desdt)

    def _false_3(_c):
        es, desdt = _c
        es = c0 + tc * (c1 + tc * (c2 + tc * (c3 + tc * (c4 + tc * (c5 + tc * (c6 + tc * (c7 + tc * c8)))))))
        desdt = d0 + tc * (d1 + tc * (d2 + tc * (d3 + tc * (d4 + tc * (d5 + tc * (d6 + tc * (d7 + tc * d8)))))))
        return (es, desdt)
    es, desdt = lax.cond(tc >= 0.0, _true_3, _false_3, (es, desdt))
    es = es * F_100P
    desdt = desdt * F_100P
    return (es, desdt)


_satvap_k = jax.jit(_satvap_k_impl, static_argnums=())


def satvap(t):
    """Host wrapper: state read from the validated numpy module."""
    return _satvap_k(t)


def _latvap_k_impl(t):
    """L116-L140 function (machine-translated)."""
    lambda_ = jnp.float64(0.0)

    def _true_1(_c):
        lambda_, = _c
        lambda_ = _clm_varcon.hvap
        return (lambda_,)

    def _false_1(_c):
        lambda_, = _c
        lambda_ = _clm_varcon.hsub
        return (lambda_,)
    lambda_, = lax.cond(t > TFRZ, _true_1, _false_1, (lambda_,))
    lambda_ = lambda_ * _mlc.mmh2o
    return lambda_


_latvap_k = jax.jit(_latvap_k_impl, static_argnums=())


def latvap(t):
    """Host wrapper: state read from the validated numpy module."""
    return _latvap_k(t)


_JAX_KERNELS = ['latvap', 'satvap']
