"""Machine-generated by recast — DO NOT EDIT."""
# source: MLLeafPhotosynthesisMod.f90 (module mlleafphotosynthesismod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters
LEAFPHOTOSYNTHESIS__TOL = np.float64('0.1')  # local param tol in leafphotosynthesis
STOMATAOPTIMIZATION__TOL = np.float64('0.001')  # local param tol in stomataoptimization

# ----- hoisted execution-part literals (zero-literal rule)
F32_2P0 = np.float64(np.float32('2.0'))  # leafphotosynthesis:271
F_0P001 = np.float64('0.001')  # cifunc:609; leafphotosynthesis:368; stomataefficiency:919
F_0P01 = np.float64('0.01')  # leafphotosynthesis:398
F_0P1 = np.float64('0.1')  # leafphotosynthesis:452
F_0P2 = np.float64('0.2')  # leafphotosynthesis:272
F_0P3 = np.float64('0.3')  # leafphotosynthesis:273
F_0P4 = np.float64('0.4')  # leafphotosynthesis:338
F_0P7 = np.float64('0.7')  # leafphotosynthesis:336
F_0P75 = np.float64('0.75')  # leafphotosynthesis:241
F_0P99 = np.float64('0.99')  # leafphotosynthesis:340
F_10P = np.float64('10.')  # leafphotosynthesis:271
F_11P = np.float64('11.')  # leafphotosynthesis:240; leafphotosynthesis:241
F_15P = np.float64('15.')  # leafphotosynthesis:272
F_1P07 = np.float64('1.07')  # leafphotosynthesis:240
F_1P3 = np.float64('1.3')  # leafphotosynthesis:274
F_1PEM06 = np.float64('1.e-06')  # leafphotosynthesis:376; leafphotosynthesis:388
F_25P = np.float64('25.')  # ft:52; fth25:99; leafphotosynthesis:271
F_2P = np.float64('2.')  # cifunc:612; cifunc:613; cifuncgs:733; stomataoptimization:827
F_35P = np.float64('35.')  # leafphotosynthesis:240; leafphotosynthesis:241
F_40P = np.float64('40.')  # leafphotosynthesis:273
F_4P = np.float64('4.')  # cifunc:542; cifuncgs:732
F_55P = np.float64('55.')  # leafphotosynthesis:274
F_659P70 = np.float64('659.70')  # leafphotosynthesis:241
F_668P39 = np.float64('668.39')  # leafphotosynthesis:240
F_8P = np.float64('8.')  # cifunc:542
F_999P = np.float64('999.')  # leafphotosynthesis:298; leafphotosynthesis:299
