"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlleaffluxesmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

DTIME_ML = np.float64('300.')  # MLclm_varctl.f90:41
