"""Machine-generated by recast — DO NOT EDIT."""
# source: MLWaterVaporMod.f90 (module mlwatervapormod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters
SATVAP__A0 = np.float64('6.11213476')  # local param a0 in satvap
SATVAP__A1 = np.float64('0.444007856')  # local param a1 in satvap
SATVAP__A2 = np.float64('0.143064234e-01')  # local param a2 in satvap
SATVAP__A3 = np.float64('0.264461437e-03')  # local param a3 in satvap
SATVAP__A4 = np.float64('0.305903558e-05')  # local param a4 in satvap
SATVAP__A5 = np.float64('0.196237241e-07')  # local param a5 in satvap
SATVAP__A6 = np.float64('0.892344772e-10')  # local param a6 in satvap
SATVAP__A7 = np.float64('-0.373208410e-12')  # local param a7 in satvap
SATVAP__A8 = np.float64('0.209339997e-15')  # local param a8 in satvap
SATVAP__B0 = np.float64('0.444017302')  # local param b0 in satvap
SATVAP__B1 = np.float64('0.286064092e-01')  # local param b1 in satvap
SATVAP__B2 = np.float64('0.794683137e-03')  # local param b2 in satvap
SATVAP__B3 = np.float64('0.121211669e-04')  # local param b3 in satvap
SATVAP__B4 = np.float64('0.103354611e-06')  # local param b4 in satvap
SATVAP__B5 = np.float64('0.404125005e-09')  # local param b5 in satvap
SATVAP__B6 = np.float64('-0.788037859e-12')  # local param b6 in satvap
SATVAP__B7 = np.float64('-0.114596802e-13')  # local param b7 in satvap
SATVAP__B8 = np.float64('0.381294516e-16')  # local param b8 in satvap
SATVAP__C0 = np.float64('6.11123516')  # local param c0 in satvap
SATVAP__C1 = np.float64('0.503109514')  # local param c1 in satvap
SATVAP__C2 = np.float64('0.188369801e-01')  # local param c2 in satvap
SATVAP__C3 = np.float64('0.420547422e-03')  # local param c3 in satvap
SATVAP__C4 = np.float64('0.614396778e-05')  # local param c4 in satvap
SATVAP__C5 = np.float64('0.602780717e-07')  # local param c5 in satvap
SATVAP__C6 = np.float64('0.387940929e-09')  # local param c6 in satvap
SATVAP__C7 = np.float64('0.149436277e-11')  # local param c7 in satvap
SATVAP__C8 = np.float64('0.262655803e-14')  # local param c8 in satvap
SATVAP__D0 = np.float64('0.503277922')  # local param d0 in satvap
SATVAP__D1 = np.float64('0.377289173e-01')  # local param d1 in satvap
SATVAP__D2 = np.float64('0.126801703e-02')  # local param d2 in satvap
SATVAP__D3 = np.float64('0.249468427e-04')  # local param d3 in satvap
SATVAP__D4 = np.float64('0.313703411e-06')  # local param d4 in satvap
SATVAP__D5 = np.float64('0.257180651e-08')  # local param d5 in satvap
SATVAP__D6 = np.float64('0.133268878e-10')  # local param d6 in satvap
SATVAP__D7 = np.float64('0.394116744e-13')  # local param d7 in satvap
SATVAP__D8 = np.float64('0.498070196e-16')  # local param d8 in satvap

# ----- hoisted execution-part literals (zero-literal rule)
F_100P = np.float64('100.')  # satvap:110; satvap:111
F_100P0 = np.float64('100.0')  # satvap:95
F_75P0 = np.float64('75.0')  # satvap:96
