"""Machine-generated by recast — DO NOT EDIT."""
# source: ColumnType.f90 (module columntype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
