"""Machine-generated by recast.transform.jax -- JAX backend (EXPERIMENTAL).

Loop-faithful lax emission from mlpftconmod_numpy.py. Cannot pass a bit-exact
gate: XLA lowers transcendentals to its own implementations and fuses
multiply-add. The gate is the ULP tier against the validated numpy module --
see recast.verify.tolerance. Do not hand-edit; fix the backend instead.
B-block provenance lives in the numpy module.
"""

import jax
import jax.numpy as jnp
import numpy as np
from jax import lax

from mlpftconmod_jax_runtime import *  # noqa: F401,F403  (enables x64, _f_* jnp shims)
from mlpftconmod_constants import *  # noqa: F401,F403
import mlpftconmod_numpy as _host

# Which device this module will run on. A ULP bound between a GPU and a CPU is
# a different claim from one between two CPUs, and the gate records what the
# module says rather than importing an accelerator to find out.
_DEVICE = str(jax.devices()[0])

from mlpftconmod_use_constants import *  # noqa: F401,F403
import clm_varpar_numpy as _clm_varpar
import mlclm_varctl_numpy as _mlc
import spmdmod_numpy as _spmdmod

_SIGNATURES = {'init': {'kind': 'subroutine', 'args': [{'name': 'this', 'dtype': 'UNKNOWN(CLASS(MLPFTCON_TYPE))', 'intent': 'UNKNOWN', 'optional': False}], 'result': None, 'result_dtype': None}, 'initallocate': {'kind': 'subroutine', 'args': [{'name': 'this', 'dtype': 'UNKNOWN(CLASS(MLPFTCON_TYPE))', 'intent': 'UNKNOWN', 'optional': False}], 'result': None, 'result_dtype': None}, 'initread': {'kind': 'subroutine', 'args': [{'name': 'this', 'dtype': 'UNKNOWN(CLASS(MLPFTCON_TYPE))', 'intent': 'UNKNOWN', 'optional': False}], 'result': None, 'result_dtype': None}}


def _init_k_impl(this):
    """L56-L63 subroutine (machine-translated)."""
    pass
    pass
    return


_init_k = jax.jit(_init_k_impl, static_argnums=())


def init(this):
    """Host wrapper: state read from the validated numpy module."""
    return _init_k(this)


initallocate = _host.initallocate


initread = _host.initread


_JAX_KERNELS = ['init']
