"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlsolarradiationmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

NUMRAD = 2  # clm_varpar.f90:20
IVIS = 1  # clm_varpar.f90:21
NLEVMLCAN = 100  # MLclm_varpar.f90:18
ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
