"""Machine-generated by recast — DO NOT EDIT."""
# source: MLSoilFluxesMod.f90 (module mlsoilfluxesmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P001 = np.float64('0.001')  # soilfluxes:116
