"""Machine-generated by recast — DO NOT EDIT."""
# source: WaterDiagnosticBulkType.f90 (module waterdiagnosticbulktype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
