"""Machine-generated by recast — DO NOT EDIT."""
# source: clm_time_manager.f90 (module clm_time_manager)

import numpy as np

# ----- module-level parameters
# SKIPPED CALKINDFLAG = 'GREGORIAN'  (unevaluated expression: 'GREGORIAN') # clm_time_manager.f90:73 (CHARACTER)
MDAY = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])  # clm_time_manager.f90:77 (INTEGER)
MDAYCUM = np.array([0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334, 365])  # clm_time_manager.f90:78 (INTEGER)
MDAYLEAP = np.array([31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])  # clm_time_manager.f90:82 (INTEGER)
MDAYLEAPCUM = np.array([0, 31, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335, 366])  # clm_time_manager.f90:83 (INTEGER)

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F32_366P = np.float64(np.float32('366.'))  # get_curr_calday:398; get_curr_calday:405; get_prev_calday:450; get_prev_calday:457
F32_367P = np.float64(np.float32('367.'))  # get_curr_calday:398; get_prev_calday:450
F_86400P = np.float64('86400.')  # get_curr_calday:386; get_curr_calday:388; get_prev_calday:438; get_prev_calday:440
I_100 = np.int32(100)  # get_curr_date:206; get_curr_date:207; get_curr_date:227; get_curr_date:232; get_curr_date:233; get_prev_date:291; get_prev_date:292; get_prev_date:312; get_prev_date:317; get_prev_date:318; isleap:142
I_10000 = np.int32(10000)  # get_curr_date:178; get_curr_date:205; get_curr_date:206; get_curr_date:227; get_curr_date:231; get_curr_date:232; get_prev_date:263; get_prev_date:290; get_prev_date:291; get_prev_date:312; get_prev_date:316; get_prev_date:317
I_13 = np.int32(13)  # get_curr_date:221; get_prev_date:306
I_365 = np.int32(365)  # get_curr_date:187; get_curr_date:196; get_prev_date:272; get_prev_date:281
I_366 = np.int32(366)  # get_curr_date:185; get_curr_date:194; get_prev_date:270; get_prev_date:279
I_4 = np.int32(4)  # isleap:140
I_400 = np.int32(400)  # isleap:144
I_86400 = np.int32(86400)  # get_curr_date:183; get_curr_date:201; get_curr_time:339; get_curr_time:340; get_prev_date:268; get_prev_date:286
