"""Machine-generated by recast — DO NOT EDIT."""
# source: WaterType.f90 (module watertype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
