"""Machine-generated by recast — DO NOT EDIT."""
# source: SoilStateType.f90 (module soilstatetype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
