"""Machine-generated by recast — DO NOT EDIT."""
# source: MLLeafBoundaryLayerMod.f90 (module mlleafboundarylayermod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P036 = np.float64('0.036')  # leafboundarylayer:115
F_0P25 = np.float64('0.25')  # leafboundarylayer:122
F_0P33 = np.float64('0.33')  # leafboundarylayer:108; leafboundarylayer:115
F_0P54 = np.float64('0.54')  # leafboundarylayer:122
F_0P66 = np.float64('0.66')  # leafboundarylayer:108
F_0P67 = np.float64('0.67')  # leafboundarylayer:110; leafboundarylayer:111; leafboundarylayer:117; leafboundarylayer:118
F_0P75 = np.float64('0.75')  # leafboundarylayer:124; leafboundarylayer:125
F_0P8 = np.float64('0.8')  # leafboundarylayer:115
F_101325P = np.float64('101325.')  # leafboundarylayer:85
F_1P81 = np.float64('1.81')  # leafboundarylayer:85
I_3 = np.int32(3)  # leafboundarylayer:146; leafboundarylayer:99
