"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module pftconmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

MXPFT = 78  # clm_varpar.f90:23
NUMRAD = 2  # clm_varpar.f90:20
IVIS = 1  # clm_varpar.f90:21
INIR = 2  # clm_varpar.f90:22
