"""Machine-generated by recast — DO NOT EDIT."""
# source: MLMathToolsMod.f90 (module mlmathtoolsmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters
HYBRID__ITMAX = np.int32(40)  # local param itmax in hybrid
ZBRENT__ITMAX = np.int32(50)  # local param itmax in zbrent
ZBRENT__EPS = np.float64('1.e-08')  # local param eps in zbrent
BISECTION__ITMAX = np.int32(100)  # local param itmax in bisection
LOG_GAMMA_FUNCTION__COEF = np.array([np.float64('76.18009172947146'), np.float64('-86.50532032941677'), np.float64('24.01409824083091'), np.float64('-1.231739572450155'), np.float64('0.1208650973866179e-02'), np.float64('-0.5395239384953e-05')])  # local param coef in log_gamma_function
LOG_GAMMA_FUNCTION__STP = np.float64('2.5066282746310005')  # local param stp in log_gamma_function
BETA_FUNCTION_INCOMPLETE_CF__MAXIT = np.int32(100)  # local param maxit in beta_function_incomplete_cf
BETA_FUNCTION_INCOMPLETE_CF__EPS = np.float64('3.e-07')  # local param eps in beta_function_incomplete_cf
BETA_FUNCTION_INCOMPLETE_CF__FPMIN = np.float64('1.e-30')  # local param fpmin in beta_function_incomplete_cf

# ----- hoisted execution-part literals (zero-literal rule)
F_1P000000000190015 = np.float64('1.000000000190015')  # log_gamma_function:531
F_1PE36 = np.float64('1.e36')  # quadratic:345
F_2P = np.float64('2.')  # beta_distribution_cdf:609; bisection:293; zbrent:203; zbrent:209; zbrent:214; zbrent:219
F_3P = np.float64('3.')  # zbrent:219
F_4P = np.float64('4.')  # quadratic:336; quadratic:338
F_5P5 = np.float64('5.5')  # log_gamma_function:529
I_6 = np.int32(6)  # log_gamma_function:532; log_gamma_function:decl
