"""Machine-generated by recast — DO NOT EDIT."""
# source: abortutils.f90 (module abortutils)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
