"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlinitverticalmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

DZ_TALL = np.float64('0.5')  # MLclm_varctl.f90:53
DZ_SHORT = np.float64('0.1')  # MLclm_varctl.f90:54
DZ_PARAM = np.float64('2.')  # MLclm_varctl.f90:55
NLAYER_ABOVE = 0  # MLclm_varctl.f90:59
NLAYER_WITHIN = 0  # MLclm_varctl.f90:60
DPAI_MIN = np.float64('0.01')  # MLclm_varctl.f90:74
NLEVMLCAN = 100  # MLclm_varpar.f90:18
MMH2O = (np.float64('18.02') * np.float64('1.e-03'))  # MLclm_varcon.f90:21
MMDRY = (np.float64('28.97') * np.float64('1.e-03'))  # MLclm_varcon.f90:20
ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
MXPFT = 78  # clm_varpar.f90:23
