"""Machine-generated by recast — DO NOT EDIT."""
# source: CanopyStateType.f90 (module canopystatetype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
