"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module clmml_driver; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

FLUX_PROFILE_TYPE = 1  # MLclm_varctl.f90:30
MET_TYPE = 0  # MLclm_varctl.f90:70
MXPFT = 78  # clm_varpar.f90:23
DENH2O = np.float64('1000.')  # clm_varcon.f90:25
NLEVGRND = (-1)  # clm_varpar.f90:18
NLEVSOI = (-1)  # clm_varpar.f90:17
TFRZ = np.float64('273.15')  # clm_varcon.f90:21
IVIS = 1  # clm_varpar.f90:21
INIR = 2  # clm_varpar.f90:22
MMDRY = (np.float64('28.97') * np.float64('1.e-03'))  # MLclm_varcon.f90:20
MMH2O = (np.float64('18.02') * np.float64('1.e-03'))  # MLclm_varcon.f90:21
ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
