"""Machine-generated by recast — DO NOT EDIT."""
# source: clm_varcon.f90 (module clm_varcon)

import numpy as np

# ----- module-level parameters
TFRZ = np.float64('273.15')  # clm_varcon.f90:21 (REAL)
SPVAL = np.float64('1.e36')  # clm_varcon.f90:44 (REAL)
ISPVAL = np.int32(-9999)  # clm_varcon.f90:45 (INTEGER)

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
