"""Machine-generated by recast — DO NOT EDIT."""
# source: clm_initializeMod.f90 (module clm_initializemod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
