"""Machine-generated by recast — DO NOT EDIT."""
# source: clmDataMod.f90 (module clmdatamod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
I_3 = np.int32(3)  # readclmsoil:decl
