"""Machine-generated by recast — DO NOT EDIT."""
# source: CLMml_driver.f90 (module clmml_driver)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_1000P = np.float64('1000.')  # output:713; output:715; output:737; output:739; readcanopyprofiles:876
F_14P = np.float64('14.')  # towerveg:data
F_17P = np.float64('17.')  # towerveg:data
F_180P = np.float64('180.')  # output:682
F_18P = np.float64('18.')  # towerveg:data
F_1PEM03 = np.float64('1.e-03')  # readcanopyprofiles:887
F_1PEM04 = np.float64('1.e-04')  # readcanopyprofiles:881
F_20P = np.float64('20.')  # towerveg:data
F_35P = np.float64('35.')  # towerveg:data
F_3P1415927 = np.float64('3.1415927')  # output:682
F_86400P = np.float64('86400.')  # clmml_drv:164; clmml_drv:240; output:650
F_999P = np.float64('999.')  # output:637
I_10 = np.int32(10)  # output:802
I_22 = np.int32(22)  # readcanopyprofiles:858; readcanopyprofiles:874; readcanopyprofiles:decl
I_3 = np.int32(3)  # clmml_drv:250; output:648; soilinit:decl
I_62 = np.int32(62)  # towerveg:data
