"""Machine-generated by recast — DO NOT EDIT."""
# source: clmSoilOptionMod.f90 (module clmsoiloptionmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
