"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module surfaceresistancemod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

DENH2O = np.float64('1000.')  # clm_varcon.f90:25
DENICE = np.float64('917.')  # clm_varcon.f90:26
