"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module controlmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

MET_TYPE = 0  # MLclm_varctl.f90:70
DPAI_MIN = np.float64('0.01')  # MLclm_varctl.f90:74
PFTCON_VAL = 0  # MLclm_varctl.f90:75
