"""Machine-generated by recast — DO NOT EDIT."""
# source: controlMod.f90 (module controlmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
I_5 = np.int32(5)  # control:89
I_60 = np.int32(60)  # control:116
I_86400 = np.int32(86400)  # control:123
