"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlcanopyfluxesmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

GRAV = np.float64('9.80665')  # clm_varcon.f90:23
SPVAL = np.float64('1.e36')  # clm_varcon.f90:44
IVIS = 1  # clm_varpar.f90:21
INIR = 2  # clm_varpar.f90:22
MMH2O = (np.float64('18.02') * np.float64('1.e-03'))  # MLclm_varcon.f90:21
RGAS = np.float64('8.31446')  # MLclm_varcon.f90:19
MLCAN_TO_CLM = 0  # MLclm_varctl.f90:64
DTIME_ML = np.float64('300.')  # MLclm_varctl.f90:41
ISPVAL = (-9999)  # clm_varcon.f90:45
ML_VERT_INIT = ISPVAL  # MLclm_varctl.f90:65
RUNGE_KUTTA_TYPE = 41  # MLclm_varctl.f90:45
NRK = ((RUNGE_KUTTA_TYPE / 10))  # MLclm_varctl.f90:49
MET_TYPE = 0  # MLclm_varctl.f90:70
ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
NLEVMLCAN = 100  # MLclm_varpar.f90:18
NLEAF = 2  # MLclm_varpar.f90:19
RPI = np.float64('3.141592654')  # clm_varcon.f90:17
NUMRAD = 2  # clm_varpar.f90:20
FLUX_PROFILE_TYPE = 1  # MLclm_varctl.f90:30
