"""Machine-generated by recast — DO NOT EDIT."""
# source: EnergyFluxType.f90 (module energyfluxtype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
