"""Machine-generated by recast — DO NOT EDIT."""
# source: fileutils.f90 (module fileutils)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
