"""Machine-generated by recast — DO NOT EDIT."""
# source: FrictionVelocityMod.f90 (module frictionvelocitymod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
