"""Machine-generated by recast — DO NOT EDIT."""
# source: initSubgridMod.f90 (module initsubgridmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
