"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module initverticalmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

NLEVSOI = (-1)  # clm_varpar.f90:17
NLEVGRND = (-1)  # clm_varpar.f90:18
ZMIN_BEDROCK = np.float64('0.4')  # clm_varcon.f90:40
