"""Machine-generated by recast — DO NOT EDIT."""
# source: initGridCellsMod.f90 (module initgridcellsmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
