"""Machine-generated by recast — DO NOT EDIT."""
# source: initVerticalMod.f90 (module initverticalmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P02 = np.float64('0.02')  # initvertical:91
F_0P04 = np.float64('0.04')  # initvertical:95
F_0P10 = np.float64('0.10')  # initvertical:99
F_100P = np.float64('100.')  # initvertical:105
F_1P5 = np.float64('1.5')  # initvertical:105
F_25P = np.float64('25.')  # initvertical:105
I_13 = np.int32(13)  # initvertical:94; initvertical:99
I_14 = np.int32(14)  # initvertical:98
I_3 = np.int32(3)  # initvertical:139; initvertical:140
I_4 = np.int32(4)  # initvertical:90; initvertical:95
I_5 = np.int32(5)  # initvertical:94
