"""Machine-generated by recast — DO NOT EDIT."""
# source: lnd_comp_nuopc.f90 (module lnd_comp_nuopc)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
