"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlcanopynitrogenprofilemod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

TFRZ = np.float64('273.15')  # clm_varcon.f90:21
JMAX25_TO_VCMAX25_NOACCLIM = np.float64('1.67')  # MLclm_varcon.f90:60
SPVAL = np.float64('1.e36')  # clm_varcon.f90:44
JMAX25_TO_VCMAX25_ACCLIM = SPVAL  # MLclm_varcon.f90:61
RD25_TO_VCMAX25_C3 = np.float64('0.015')  # MLclm_varcon.f90:62
RD25_TO_VCMAX25_C4 = np.float64('0.025')  # MLclm_varcon.f90:63
KP25_TO_VCMAX25_C4 = np.float64('0.02')  # MLclm_varcon.f90:64
ACCLIM_TYPE = 1  # MLclm_varctl.f90:22
KN_VAL = (-np.float64('999.'))  # MLclm_varctl.f90:23
LEAF_OPTICS_TYPE = 0  # MLclm_varctl.f90:36
ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
