"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlcanopywatermod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

DEWMX = np.float64('0.1')  # MLclm_varcon.f90:98
MAXIMUM_LEAF_WETTED_FRACTION = np.float64('0.05')  # MLclm_varcon.f90:99
FWET_EXPONENT = np.float64('0.67')  # MLclm_varcon.f90:101
INTERCEPTION_FRACTION = np.float64('1.0')  # MLclm_varcon.f90:100
DTIME_ML = np.float64('300.')  # MLclm_varctl.f90:41
MMH2O = (np.float64('18.02') * np.float64('1.e-03'))  # MLclm_varcon.f90:21
ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
