"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlcanopyturbulencemod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

TURB_TYPE = 1  # MLclm_varctl.f90:27
MMH2O = (np.float64('18.02') * np.float64('1.e-03'))  # MLclm_varcon.f90:21
MMDRY = (np.float64('28.97') * np.float64('1.e-03'))  # MLclm_varcon.f90:20
CD = np.float64('0.25')  # MLclm_varcon.f90:119
ETA_MAX = np.float64('20.')  # MLclm_varcon.f90:138
GRAV = np.float64('9.80665')  # clm_varcon.f90:23
VKC = np.float64('0.4')  # clm_varcon.f90:24
SPARSE_CANOPY_TYPE = 1  # MLclm_varctl.f90:28
BETA_NEUTRAL_MAX = np.float64('0.35')  # MLclm_varcon.f90:120
CR = np.float64('0.3')  # MLclm_varcon.f90:121
Z0MG = np.float64('0.01')  # MLclm_varcon.f90:126
LCL_MIN = (-np.float64('2.'))  # MLclm_varcon.f90:134
LCL_MAX = np.float64('1.')  # MLclm_varcon.f90:135
PR0 = np.float64('0.5')  # MLclm_varcon.f90:123
PR1 = np.float64('0.3')  # MLclm_varcon.f90:124
PR2 = np.float64('2.0')  # MLclm_varcon.f90:125
C2 = np.float64('0.5')  # MLclm_varcon.f90:122
RPI = np.float64('3.141592654')  # clm_varcon.f90:17
NZ = 276  # MLclm_varcon.f90:145
NL = 41  # MLclm_varcon.f90:145
HF_EXTENSION_TYPE = 2  # MLclm_varctl.f90:29
RA_MAX = np.float64('500.')  # MLclm_varcon.f90:137
