"""Machine-generated by recast — DO NOT EDIT."""
# source: MLCanopyFluxesMod.f90 (module mlcanopyfluxesmod)

import numpy as np

# ----- module-level parameters
NVAR1D = np.int32(23)  # MLCanopyFluxesMod.f90:35 (INTEGER)
NVAR2D = np.int32(14)  # MLCanopyFluxesMod.f90:36 (INTEGER)
NVAR3D = np.int32(12)  # MLCanopyFluxesMod.f90:37 (INTEGER)

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P001 = np.float64('0.001')  # canopyfluxesdiagnostics:1411; canopyfluxesdiagnostics:1428
F_0P01 = np.float64('0.01')  # canopyfluxesdiagnostics:1418; getclmvar:863
F_180P = np.float64('180.')  # getclmvar:860; getclmvar:861
F_1PE03 = np.float64('1.e03')  # getclmvar:812
F_1PE06 = np.float64('1.e06')  # getclmvar:811
F_1PEM03 = np.float64('1.e-03')  # canopyfluxesdiagnostics:1364; mlcanopyfluxes:402
F_1PEM06 = np.float64('1.e-06')  # mlcanopyfluxes:380
F_2P = np.float64('2.')  # canopyfluxesdiagnostics:1493
F_86400P = np.float64('86400.')  # mlcanopyfluxes:253; mlcanopyfluxes:258; mlcanopyfluxes:259; mlcanopyfluxes:414; mlcanopyfluxes:417
I_10 = np.int32(10)  # mlcanopyfluxes:463; mlcanopyfluxes:466
I_20 = np.int32(20)  # mlcanopyfluxes:465
I_3 = np.int32(3)  # mlcanopyfluxes:255; mlcanopyfluxes:415
I_36 = np.int32(36)  # mlcanopyfluxes:573
