"""Machine-generated by recast — DO NOT EDIT."""
# source: MLclm_varctl.f90 (module mlclm_varctl)

import numpy as np

# ----- module-level parameters
RUNGE_KUTTA_TYPE = np.int32(41)  # MLclm_varctl.f90:45 (INTEGER)
NRK = ( RUNGE_KUTTA_TYPE / 10 )  # MLclm_varctl.f90:49 (INTEGER)

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
