"""Machine-generated by recast — DO NOT EDIT."""
# source: MLclm_varpar.f90 (module mlclm_varpar)

import numpy as np

# ----- module-level parameters
NLEVMLCAN = np.int32(100)  # MLclm_varpar.f90:18 (INTEGER)
NLEAF = np.int32(2)  # MLclm_varpar.f90:19 (INTEGER)
ISUN = np.int32(1)  # MLclm_varpar.f90:20 (INTEGER)
ISHA = np.int32(2)  # MLclm_varpar.f90:21 (INTEGER)

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
