"""Machine-generated by recast — DO NOT EDIT."""
# source: MLclm_varcon.f90 (module mlclm_varcon)

import numpy as np

# ----- module-level parameters
NZ = np.int32(276)  # MLclm_varcon.f90:145 (INTEGER)
NL = np.int32(41)  # MLclm_varcon.f90:145 (INTEGER)

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
