"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlleafheatcapacitymod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

CPLIQ = np.float64('4.188e3')  # clm_varcon.f90:34
CPBIO = (np.float64('4188.') / np.float64('3.'))  # MLclm_varcon.f90:86
FCARBON = np.float64('0.5')  # MLclm_varcon.f90:87
FWATER = np.float64('0.7')  # MLclm_varcon.f90:88
