"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlleafboundarylayermod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

TFRZ = np.float64('273.15')  # clm_varcon.f90:21
GRAV = np.float64('9.80665')  # clm_varcon.f90:23
VISC0 = np.float64('13.3e-06')  # MLclm_varcon.f90:24
DH0 = np.float64('18.9e-06')  # MLclm_varcon.f90:25
DV0 = np.float64('21.8e-06')  # MLclm_varcon.f90:26
DC0 = np.float64('13.8e-06')  # MLclm_varcon.f90:27
GB_FACTOR = np.float64('1.5')  # MLclm_varcon.f90:93
GBH_MIN = np.float64('0.2')  # MLclm_varcon.f90:136
GB_TYPE = 3  # MLclm_varctl.f90:31
