"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlleafphotosynthesismod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

TFRZ = np.float64('273.15')  # clm_varcon.f90:21
RGAS = np.float64('8.31446')  # MLclm_varcon.f90:19
KC25 = np.float64('404.9')  # MLclm_varcon.f90:35
KO25 = np.float64('278.4')  # MLclm_varcon.f90:37
CP25 = np.float64('42.75')  # MLclm_varcon.f90:39
KCHA = np.float64('79430.')  # MLclm_varcon.f90:36
KOHA = np.float64('36380.')  # MLclm_varcon.f90:38
CPHA = np.float64('37830.')  # MLclm_varcon.f90:40
VCMAXHA_NOACCLIM = np.float64('65330.')  # MLclm_varcon.f90:42
VCMAXHA_ACCLIM = np.float64('72000.')  # MLclm_varcon.f90:43
JMAXHA_NOACCLIM = np.float64('43540.')  # MLclm_varcon.f90:49
JMAXHA_ACCLIM = np.float64('50000.')  # MLclm_varcon.f90:50
VCMAXHD_NOACCLIM = np.float64('150000.')  # MLclm_varcon.f90:44
VCMAXHD_ACCLIM = np.float64('200000.')  # MLclm_varcon.f90:45
JMAXHD_NOACCLIM = np.float64('150000.')  # MLclm_varcon.f90:51
JMAXHD_ACCLIM = np.float64('200000.')  # MLclm_varcon.f90:52
VCMAXSE_NOACCLIM = np.float64('490.')  # MLclm_varcon.f90:46
SPVAL = np.float64('1.e36')  # clm_varcon.f90:44
VCMAXSE_ACCLIM = SPVAL  # MLclm_varcon.f90:47
JMAXSE_NOACCLIM = np.float64('490.')  # MLclm_varcon.f90:53
JMAXSE_ACCLIM = SPVAL  # MLclm_varcon.f90:54
RDHA = np.float64('46390.')  # MLclm_varcon.f90:56
RDHD = np.float64('150000.')  # MLclm_varcon.f90:57
RDSE = np.float64('490.')  # MLclm_varcon.f90:58
PHI_PSII = np.float64('0.70')  # MLclm_varcon.f90:66
THETA_J = np.float64('0.90')  # MLclm_varcon.f90:68
VPD_MIN_MED = np.float64('100.')  # MLclm_varcon.f90:81
RH_MIN_BB = np.float64('0.2')  # MLclm_varcon.f90:80
DH2O_TO_DCO2 = np.float64('1.6')  # MLclm_varcon.f90:79
GS_TYPE = 2  # MLclm_varctl.f90:18
ACCLIM_TYPE = 1  # MLclm_varctl.f90:22
GSPOT_TYPE = 1  # MLclm_varctl.f90:19
QE_C4 = np.float64('0.05')  # MLclm_varcon.f90:69
GS_SOLVER = 2  # MLclm_varctl.f90:20
COLIM_C3A = np.float64('0.98')  # MLclm_varcon.f90:71
COLIM_C4A = np.float64('0.80')  # MLclm_varcon.f90:73
COLIM_C4B = np.float64('0.95')  # MLclm_varcon.f90:74
COLIM_TYPE = 1  # MLclm_varctl.f90:21
