"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mllongwaveradiationmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

LONGWAVE_TYPE = 1  # MLclm_varctl.f90:37
SB = np.float64('5.67e-08')  # clm_varcon.f90:22
EMG = np.float64('0.96')  # MLclm_varcon.f90:114
ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
NLEVMLCAN = 100  # MLclm_varpar.f90:18
