"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlplanthydraulicsmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

RPI = np.float64('3.141592654')  # clm_varcon.f90:17
DENH2O = np.float64('1000.')  # clm_varcon.f90:25
GRAV = np.float64('9.80665')  # clm_varcon.f90:23
NLEVSOI = (-1)  # clm_varpar.f90:17
MMH2O = (np.float64('18.02') * np.float64('1.e-03'))  # MLclm_varcon.f90:21
DTIME_ML = np.float64('300.')  # MLclm_varctl.f90:41
