"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlrungekuttamod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
RUNGE_KUTTA_TYPE = 41  # MLclm_varctl.f90:45
NRK = ((RUNGE_KUTTA_TYPE / 10))  # MLclm_varctl.f90:49
SPVAL = np.float64('1.e36')  # clm_varcon.f90:44
