"""Machine-generated by recast — DO NOT EDIT."""
# source: MLSolarRadiationMod.f90 (module mlsolarradiationmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters
# SKIPPED local NORMAN__NEQ = (nlevmlcan + 1) * 2 (unknown name 'nlevmlcan' in expression: (nlevmlcan + 1) * 2)
TWOSTREAM__UNITB = np.float64('1.')  # local param unitb in twostream
TWOSTREAM__UNITD = np.float64('1.')  # local param unitd in twostream

# ----- hoisted execution-part literals (zero-literal rule)
F_0P01 = np.float64('0.01')  # solarradiation:173
F_0P330 = np.float64('0.330')  # solarradiation:177
F_0P633 = np.float64('0.633')  # solarradiation:177
F_0P877 = np.float64('0.877')  # solarradiation:178
F_10P = np.float64('10.')  # solarradiation:207; solarradiation:212
F_180P = np.float64('180.')  # solarradiation:207; solarradiation:212
F_1PEM03 = np.float64('1.e-03')  # norman:562; norman:569
F_1PEM06 = np.float64('1.e-06')  # solarradiation:156; solarradiation:157; twostream:869
F_2P = np.float64('2.')  # solarradiation:178; solarradiation:212; solarradiation:247; twostream:719; twostream:720; twostream:736; twostream:738
F_5P = np.float64('5.')  # solarradiation:207
I_9 = np.int32(9)  # solarradiation:206
