"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlsolarradiationmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

RPI = np.float64('3.141592654')  # clm_varcon.f90:17
NUMRAD = 2  # clm_varpar.f90:20
IVIS = 1  # clm_varpar.f90:21
CHIL_MAX = np.float64('0.6')  # MLclm_varcon.f90:107
CHIL_MIN = (-np.float64('0.4'))  # MLclm_varcon.f90:106
KB_MAX = np.float64('40.')  # MLclm_varcon.f90:108
J_TO_UMOL = np.float64('4.6')  # MLclm_varcon.f90:109
LIGHT_TYPE = 2  # MLclm_varctl.f90:35
LEAF_OPTICS_TYPE = 0  # MLclm_varctl.f90:36
NLEVMLCAN = 100  # MLclm_varpar.f90:18
ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
