"""Machine-generated by recast — DO NOT EDIT."""
# source: MLSoilTemperatureMod.f90 (module mlsoiltemperaturemod)

import numpy as np

# ----- module-level parameters
THIN_SFCLAYER = np.float64('1.0e-6')  # MLSoilTemperatureMod.f90:35 (REAL)

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F32_1P0EM3 = np.float64(np.float32('1.0e-3'))  # soilthermprop:310
F_0P1EM6 = np.float64('0.1e-6')  # soilthermprop:265
F_1P105EM6 = np.float64('1.105e-6')  # soilthermprop:286
F_1PEM06 = np.float64('1.e-06')  # soiltemperature:186
F_7P75EM5 = np.float64('7.75e-5')  # soilthermprop:286
