"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlsoiltemperaturemod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

NLEVGRND = (-1)  # clm_varpar.f90:18
NLEVSNO = (-1)  # clm_varpar.f90:16
DENH2O = np.float64('1000.')  # clm_varcon.f90:25
DENICE = np.float64('917.')  # clm_varcon.f90:26
TFRZ = np.float64('273.15')  # clm_varcon.f90:21
TKWAT = np.float64('0.57')  # clm_varcon.f90:27
TKICE = np.float64('2.29')  # clm_varcon.f90:28
TKAIR = np.float64('0.023')  # clm_varcon.f90:29
CPICE = np.float64('2.11727e3')  # clm_varcon.f90:33
CPLIQ = np.float64('4.188e3')  # clm_varcon.f90:34
THK_BEDROCK = np.float64('3.0')  # clm_varcon.f90:38
CSOL_BEDROCK = np.float64('2.0e6')  # clm_varcon.f90:39
