"""Machine-generated by recast — DO NOT EDIT."""
# source: ncdio_pio.f90 (module ncdio_pio)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
