"""Machine-generated by recast — DO NOT EDIT."""
# source: PatchType.f90 (module patchtype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
