"""Machine-generated by recast — DO NOT EDIT."""
# source: restUtilMod.f90 (module restutilmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
