"""Machine-generated by recast — DO NOT EDIT."""
# source: shr_kind_mod.f90 (module shr_kind_mod)

import numpy as np

# ----- module-level parameters
SHR_KIND_R8 = np.int32(8)  # shr_kind_mod.f90:10 (INTEGER)
# SKIPPED SHR_KIND_IN = KIND(1)  (kind parameter (compile-time only)) # shr_kind_mod.f90:11 (INTEGER)

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
