"""Machine-generated by recast — DO NOT EDIT."""
# source: shr_file_mod.f90 (module shr_file_mod)

import numpy as np

# ----- module-level parameters
SHR_FILE_MINUNIT = np.int32(10)  # shr_file_mod.f90:15 (INTEGER)
SHR_FILE_MAXUNIT = np.int32(99)  # shr_file_mod.f90:16 (INTEGER)

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
I_5 = np.int32(5)  # shr_file_freeunit:100; shr_file_getunit:53; shr_file_getunit:67
I_6 = np.int32(6)  # shr_file_freeunit:100; shr_file_getunit:53; shr_file_getunit:67
