"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module shr_orb_mod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

RPI = np.float64('3.141592654')  # clm_varcon.f90:17
