"""Machine-generated by recast — DO NOT EDIT."""
# source: SoilWaterMovementMod.f90 (module soilwatermovementmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P01 = np.float64('0.01')  # compute_hydraulic_properties:156
F_1P0EM6 = np.float64('1.0e-6')  # soilwater_moisture_form:100
F_1PE08 = np.float64('1.e08')  # compute_hydraulic_properties:159
F_2P = np.float64('2.')  # compute_hydraulic_properties:157
F_3P = np.float64('3.')  # compute_hydraulic_properties:157
