"""Machine-generated by recast — DO NOT EDIT."""
# source: SoilTexMod.f90 (module soiltexmod)

import numpy as np

# ----- module-level parameters
NTEX = np.int32(11)  # SoilTexMod.f90:17 (INTEGER)

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
