"""Machine-generated by recast — DO NOT EDIT."""
# source: SoilStateInitTimeConstMod.f90 (module soilstateinittimeconstmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters
SOILSTATEINITTIMECONST__ORGANIC_MAX = np.float64('130.')  # local param organic_max in soilstateinittimeconst
SOILSTATEINITTIMECONST__ZSAPRIC = np.float64('0.5')  # local param zsapric in soilstateinittimeconst
SOILSTATEINITTIMECONST__PCALPHA = np.float64('0.5')  # local param pcalpha in soilstateinittimeconst
SOILSTATEINITTIMECONST__PCBETA = np.float64('0.139')  # local param pcbeta in soilstateinittimeconst
SOILSTATEINITTIMECONST__M_TO_CM = np.float64('1.e2')  # local param m_to_cm in soilstateinittimeconst

# ----- hoisted execution-part literals (zero-literal rule)
F_0P00126 = np.float64('0.00126')  # soilstateinittimeconst:193
F_0P0070556 = np.float64('0.0070556')  # soilstateinittimeconst:195
F_0P0131 = np.float64('0.0131')  # soilstateinittimeconst:194
F_0P0153 = np.float64('0.0153')  # soilstateinittimeconst:195
F_0P05 = np.float64('0.05')  # soilstateinittimeconst:246
F_0P1 = np.float64('0.1')  # soilstateinittimeconst:206
F_0P135 = np.float64('0.135')  # soilstateinittimeconst:249; soilstateinittimeconst:253
F_0P159 = np.float64('0.159')  # soilstateinittimeconst:196
F_0P2 = np.float64('0.2')  # soilstateinittimeconst:207
F_0P25 = np.float64('0.25')  # soilstateinittimeconst:259
F_0P2799 = np.float64('0.2799')  # soilstateinittimeconst:208
F_0P28 = np.float64('0.28')  # soilstateinittimeconst:208
F_0P489 = np.float64('0.489')  # soilstateinittimeconst:193
F_0P83 = np.float64('0.83')  # soilstateinittimeconst:206
F_0P884 = np.float64('0.884')  # soilstateinittimeconst:195
F_0P93 = np.float64('0.93')  # soilstateinittimeconst:206
F_0P947 = np.float64('0.947')  # soilstateinittimeconst:249; soilstateinittimeconst:253
F_100P = np.float64('100.')  # soilstateinittimeconst:167; soilstateinittimeconst:168
F_10P = np.float64('10.')  # soilstateinittimeconst:194; soilstateinittimeconst:195
F_10P1 = np.float64('10.1')  # soilstateinittimeconst:207
F_10P3 = np.float64('10.3')  # soilstateinittimeconst:207
F_12P0 = np.float64('12.0')  # soilstateinittimeconst:209
F_1P88 = np.float64('1.88')  # soilstateinittimeconst:194
F_1P926E06 = np.float64('1.926e06')  # soilstateinittimeconst:273
F_1PE6 = np.float64('1.e6')  # soilstateinittimeconst:271
F_2700P = np.float64('2700.')  # soilstateinittimeconst:248; soilstateinittimeconst:249; soilstateinittimeconst:252; soilstateinittimeconst:253
F_2P128 = np.float64('2.128')  # soilstateinittimeconst:271
F_2P385 = np.float64('2.385')  # soilstateinittimeconst:271
F_2P5E06 = np.float64('2.5e06')  # soilstateinittimeconst:275
F_2P7 = np.float64('2.7')  # soilstateinittimeconst:209
F_2P91 = np.float64('2.91')  # soilstateinittimeconst:196
F_2P92 = np.float64('2.92')  # soilstateinittimeconst:261
F_3P = np.float64('3.')  # soilstateinittimeconst:265
F_60P = np.float64('60.')  # soilstateinittimeconst:200
F_64P7 = np.float64('64.7')  # soilstateinittimeconst:249; soilstateinittimeconst:253
F_8P80 = np.float64('8.80')  # soilstateinittimeconst:261
F_9P3 = np.float64('9.3')  # soilstateinittimeconst:209
