"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module soilstateinittimeconstmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

CSOL_BEDROCK = np.float64('2.0e6')  # clm_varcon.f90:39
NLEVSOI = (-1)  # clm_varpar.f90:17
NLEVGRND = (-1)  # clm_varpar.f90:18
