"""Machine-generated by recast — DO NOT EDIT."""
# source: spmdMod.f90 (module spmdmod)

import numpy as np

# ----- module-level parameters
MASTERPROC = True  # spmdMod.f90:16 (LOGICAL)

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
