"""Machine-generated by recast — DO NOT EDIT."""
# source: SurfaceResistanceMod.f90 (module surfaceresistancemod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F32_0P8 = np.float64(np.float32('0.8'))  # calc_soil_resistance_sl14:114
F32_1P75 = np.float64(np.float32('1.75'))  # calc_soil_resistance_sl14:111
F32_1PE3 = np.float64(np.float32('1.e3'))  # calc_soil_resistance_sl14:117
F32_273P15 = np.float64(np.float32('273.15'))  # calc_soil_resistance_sl14:111
F32_2P12EM5 = np.float64(np.float32('2.12e-5'))  # calc_soil_resistance_sl14:111
F_0P001 = np.float64('0.001')  # calc_soil_resistance_sl14:114
F_0P01 = np.float64('0.01')  # calc_soil_resistance_sl14:109
F_15P = np.float64('15.')  # calc_soil_resistance_sl14:114
F_1P0EM6 = np.float64('1.0e-6')  # calc_soil_resistance_sl14:108
F_1PE6 = np.float64('1.e6')  # calc_soil_resistance_sl14:118
F_1PE7 = np.float64('1.e7')  # calc_soil_resistance_sl14:110
F_200P = np.float64('200.')  # calc_soil_resistance_sl14:116
F_20P = np.float64('20.')  # calc_soil_resistance_sl14:117
F_3P = np.float64('3.')  # calc_soil_resistance_sl14:113
