"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module towermetmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

SB = np.float64('5.67e-08')  # clm_varcon.f90:22
IVIS = 1  # clm_varpar.f90:21
INIR = 2  # clm_varpar.f90:22
MMH2O = (np.float64('18.02') * np.float64('1.e-03'))  # MLclm_varcon.f90:21
MMDRY = (np.float64('28.97') * np.float64('1.e-03'))  # MLclm_varcon.f90:20
