"""Machine-generated by recast — DO NOT EDIT."""
# source: wateratm2lndBulkType.f90 (module wateratm2lndbulktype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
