"""Machine-generated by recast — DO NOT EDIT."""
# source: WaterStateBulkType.f90 (module waterstatebulktype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
