"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module waterstatebulktype; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

NLEVGRND = (-1)  # clm_varpar.f90:18
NLEVSNO = (-1)  # clm_varpar.f90:16
ISPVAL = (-9999)  # clm_varcon.f90:45
SPVAL = np.float64('1.e36')  # clm_varcon.f90:44
