"""Machine-generated by recast — DO NOT EDIT."""
# source: MLRungeKuttaMod.f90 (module mlrungekuttamod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_2P = np.float64('2.')  # rungekuttaini:227; rungekuttaini:228; rungekuttaini:236; rungekuttaini:243; rungekuttaini:248; rungekuttaini:255; rungekuttaini:265; rungekuttaini:274; rungekuttaini:280; rungekuttaini:287; rungekuttaini:292; rungekuttaini:299; rungekuttaini:303; rungekuttaini:311; rungekuttaini:319; rungekuttaini:324; rungekuttaini:333; rungekuttaini:334; rungekuttaini:338; rungekuttaini:339
F_3P = np.float64('3.')  # rungekuttaini:248; rungekuttaini:252; rungekuttaini:255; rungekuttaini:261; rungekuttaini:265; rungekuttaini:270; rungekuttaini:273; rungekuttaini:274; rungekuttaini:284; rungekuttaini:288; rungekuttaini:293
F_4P = np.float64('4.')  # rungekuttaini:251; rungekuttaini:252; rungekuttaini:268; rungekuttaini:270; rungekuttaini:284; rungekuttaini:289; rungekuttaini:293; rungekuttaini:307
F_6P = np.float64('6.')  # rungekuttaini:306; rungekuttaini:307; rungekuttaini:308; rungekuttaini:332; rungekuttaini:333; rungekuttaini:334; rungekuttaini:335
F_9P = np.float64('9.')  # rungekuttaini:287; rungekuttaini:288; rungekuttaini:289
I_21 = np.int32(21)  # rungekuttaini:220
I_22 = np.int32(22)  # rungekuttaini:232
I_23 = np.int32(23)  # rungekuttaini:244
I_3 = np.int32(3)  # rungekuttaini:260; rungekuttaini:263; rungekuttaini:264; rungekuttaini:265; rungekuttaini:266; rungekuttaini:270; rungekuttaini:274; rungekuttaini:279; rungekuttaini:282; rungekuttaini:283; rungekuttaini:284; rungekuttaini:285; rungekuttaini:289; rungekuttaini:293; rungekuttaini:298; rungekuttaini:301; rungekuttaini:302; rungekuttaini:303; rungekuttaini:304; rungekuttaini:308; rungekuttaini:312; rungekuttaini:317; rungekuttaini:321; rungekuttaini:323; rungekuttaini:324; rungekuttaini:325; rungekuttaini:326; rungekuttaini:329; rungekuttaini:334; rungekuttaini:339
I_31 = np.int32(31)  # rungekuttaini:256
I_32 = np.int32(32)  # rungekuttaini:275
I_33 = np.int32(33)  # rungekuttaini:294
I_4 = np.int32(4)  # rungekuttaini:318; rungekuttaini:322; rungekuttaini:326; rungekuttaini:327; rungekuttaini:328; rungekuttaini:329; rungekuttaini:330; rungekuttaini:335; rungekuttaini:340
I_41 = np.int32(41)  # rungekuttaini:313
