"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlcanopynitrogenprofilemod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

TFRZ = np.float64('273.15')  # clm_varcon.f90:21
ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
