"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlgetatmforcingmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

IVIS = 1  # clm_varpar.f90:21
INIR = 2  # clm_varpar.f90:22
MET_TYPE = 0  # MLclm_varctl.f90:70
MMH2O = (np.float64('18.02') * np.float64('1.e-03'))  # MLclm_varcon.f90:21
MMDRY = (np.float64('28.97') * np.float64('1.e-03'))  # MLclm_varcon.f90:20
CPD = np.float64('1005.')  # MLclm_varcon.f90:22
CPW = np.float64('1846.')  # MLclm_varcon.f90:23
RGAS = np.float64('8.31446')  # MLclm_varcon.f90:19
LAPSE_RATE = np.float64('0.0098')  # MLclm_varcon.f90:28
WIND_FORC_MIN = np.float64('0.5')  # MLclm_varcon.f90:133
