"""Machine-generated by recast — DO NOT EDIT."""
# source: GridcellType.f90 (module gridcelltype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
