"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module gridcelltype; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

SPVAL = np.float64('1.e36')  # clm_varcon.f90:44
