"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlcanopyfluxesmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

SPVAL = np.float64('1.e36')  # clm_varcon.f90:44
IVIS = 1  # clm_varpar.f90:21
INIR = 2  # clm_varpar.f90:22
RUNGE_KUTTA_TYPE = 41  # MLclm_varctl.f90:45
NRK = ((RUNGE_KUTTA_TYPE // 10))  # MLclm_varctl.f90:49
ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
NLEVMLCAN = 100  # MLclm_varpar.f90:18
NLEAF = 2  # MLclm_varpar.f90:19
NUMRAD = 2  # clm_varpar.f90:20
