"""Machine-generated by recast — DO NOT EDIT."""
# source: MLCanopyTurbulenceMod.f90 (module mlcanopyturbulencemod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P001 = np.float64('0.001')  # roughnesslength:892
F_0P1 = np.float64('0.1')  # aerodynamicconductance:1123; aerodynamicconductance:1147; getobu:247
F_0P25 = np.float64('0.25')  # obufunc:369
F_0P61 = np.float64('0.61')  # obufunc:416
F_100P = np.float64('100.')  # getobu:245; getobu:246
F_16P = np.float64('16.')  # getbeta:451; phic_monin_obukhov:665; phim_monin_obukhov:640; psic_monin_obukhov:719; psim_monin_obukhov:692
F_1PEM06 = np.float64('1.e-06')  # aerodynamicconductance:1091; getbeta:476
F_27P = np.float64('27.')  # getbeta:463; getbeta:465
F_2P = np.float64('2.')  # getbeta:453; getbeta:463; getbeta:465; getpsirsl:575; getpsirsl:608; hf2008:175; hf2008:199; obufunc:356; psic_monin_obukhov:720; psim_monin_obukhov:693; roughnesslength:909
F_3P = np.float64('3.')  # getbeta:463; getbeta:466; getbeta:467
F_4P = np.float64('4.')  # getbeta:453; getbeta:463
F_5P = np.float64('5.')  # getbeta:459; phic_monin_obukhov:667; phim_monin_obukhov:642; psic_monin_obukhov:722; psim_monin_obukhov:695
F_9P = np.float64('9.')  # getbeta:463; getbeta:465
I_20 = np.int32(20)  # roughnesslength:893
I_3 = np.int32(3)  # getbeta:463; getbeta:465; hf2008:175; obufunc:360
I_4 = np.int32(4)  # getbeta:451; getbeta:452
