"""Machine-generated by recast — DO NOT EDIT."""
# source: MLCanopyNitrogenProfileMod.f90 (module mlcanopynitrogenprofilemod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P00963 = np.float64('0.00963')  # canopynitrogenprofile:120
F_0P035 = np.float64('0.035')  # canopynitrogenprofile:97
F_11P = np.float64('11.')  # canopynitrogenprofile:97
F_1PEM06 = np.float64('1.e-06')  # canopynitrogenprofile:200
F_2P43 = np.float64('2.43')  # canopynitrogenprofile:120
F_2P59 = np.float64('2.59')  # canopynitrogenprofile:97
F_35P = np.float64('35.')  # canopynitrogenprofile:97
