"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlgetatmforcingmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

IVIS = 1  # clm_varpar.f90:21
INIR = 2  # clm_varpar.f90:22
