"""Machine-generated by recast — DO NOT EDIT."""
# source: MLinitVerticalMod.f90 (module mlinitverticalmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P1 = np.float64('0.1')  # initverticalprofiles:396
F_11P5 = np.float64('11.5')  # getpadparameters:447
F_1PE06 = np.float64('1.e06')  # initverticalprofiles:393
F_1PEM06 = np.float64('1.e-06')  # initverticalstructure:234; initverticalstructure:292; initverticalstructure:297
F_1PEM10 = np.float64('1.e-10')  # initverticalstructure:167
F_2P0 = np.float64('2.0')  # getpadparameters:451; getpadparameters:455; getpadparameters:460; getpadparameters:465
F_2P5 = np.float64('2.5')  # getpadparameters:472
F_3P5 = np.float64('3.5')  # getpadparameters:447; getpadparameters:451; getpadparameters:455; getpadparameters:460; getpadparameters:465
F_999P = np.float64('999.')  # getpadparameters:443; getpadparameters:444
I_11 = np.int32(11)  # getpadparameters:465
I_12 = np.int32(12)  # getpadparameters:472
I_16 = np.int32(16)  # getpadparameters:472
I_3 = np.int32(3)  # getpadparameters:451
I_4 = np.int32(4)  # getpadparameters:455
I_5 = np.int32(5)  # getpadparameters:455
I_6 = np.int32(6)  # getpadparameters:460
I_8 = np.int32(8)  # getpadparameters:460
I_9 = np.int32(9)  # getpadparameters:465
