"""Machine-generated by recast — DO NOT EDIT."""
# source: SurfaceAlbedoType.f90 (module surfacealbedotype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
