"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module wateratm2lndbulktype; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

NUMRAD = 2  # clm_varpar.f90:20
