"""Machine-generated by recast.transform.jax -- JAX backend (EXPERIMENTAL).

Loop-faithful lax emission from columntype_numpy.py. Cannot pass a bit-exact
gate: XLA lowers transcendentals to its own implementations and fuses
multiply-add. The gate is the ULP tier against the validated numpy module --
see recast.verify.tolerance. Do not hand-edit; fix the backend instead.
B-block provenance lives in the numpy module.
"""

import jax
import jax.numpy as jnp
import numpy as np
from jax import lax

from columntype_jax_runtime import *  # noqa: F401,F403  (enables x64, _f_* jnp shims)
from columntype_constants import *  # noqa: F401,F403
import columntype_numpy as _host

# Which device this module will run on. A ULP bound between a GPU and a CPU is
# a different claim from one between two CPUs, and the gate records what the
# module says rather than importing an accelerator to find out.
_DEVICE = str(jax.devices()[0])

from columntype_use_constants import *  # noqa: F401,F403
import clm_varcon_numpy as _clm_varcon
import clm_varpar_numpy as _clm_varpar

_SIGNATURES = {'init': {'kind': 'subroutine', 'args': [{'name': 'this', 'dtype': 'UNKNOWN(CLASS(COLUMN_TYPE))', 'intent': 'UNKNOWN', 'optional': False}, {'name': 'begc', 'dtype': 'int32', 'intent': 'IN', 'optional': False}, {'name': 'endc', 'dtype': 'int32', 'intent': 'IN', 'optional': False}], 'result': None, 'result_dtype': None}}


init = _host.init


_JAX_KERNELS = []
