"""Machine-generated by recast.transform.jax -- JAX backend (EXPERIMENTAL).

Loop-faithful lax emission from energyfluxtype_numpy.py. Cannot pass a bit-exact
gate: XLA lowers transcendentals to its own implementations and fuses
multiply-add. The gate is the ULP tier against the validated numpy module --
see recast.verify.tolerance. Do not hand-edit; fix the backend instead.
B-block provenance lives in the numpy module.
"""

import jax
import jax.numpy as jnp
import numpy as np
from jax import lax

from energyfluxtype_jax_runtime import *  # noqa: F401,F403  (enables x64, _f_* jnp shims)
from energyfluxtype_constants import *  # noqa: F401,F403
import energyfluxtype_numpy as _host

# Which device this module will run on. A ULP bound between a GPU and a CPU is
# a different claim from one between two CPUs, and the gate records what the
# module says rather than importing an accelerator to find out.
_DEVICE = str(jax.devices()[0])

from energyfluxtype_use_constants import *  # noqa: F401,F403
import clm_varcon_numpy as _clm_varcon

_SIGNATURES = {'init': {'kind': 'subroutine', 'args': [{'name': 'this', 'dtype': 'UNKNOWN(CLASS(ENERGYFLUX_TYPE))', 'intent': 'UNKNOWN', 'optional': False}, {'name': 'bounds', 'dtype': 'UNKNOWN(TYPE(BOUNDS_TYPE))', 'intent': 'IN', 'optional': False}], 'result': None, 'result_dtype': None}, 'initallocate': {'kind': 'subroutine', 'args': [{'name': 'this', 'dtype': 'UNKNOWN(CLASS(ENERGYFLUX_TYPE))', 'intent': 'UNKNOWN', 'optional': False}, {'name': 'bounds', 'dtype': 'UNKNOWN(TYPE(BOUNDS_TYPE))', 'intent': 'IN', 'optional': False}], 'result': None, 'result_dtype': None}}


init = _host.init


initallocate = _host.initallocate


_JAX_KERNELS = []
