"""Machine-generated by recast — DO NOT EDIT."""
# source: MLLongwaveRadiationMod.f90 (module mllongwaveradiationmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters
# SKIPPED local NORMAN__NEQ = (nlevmlcan + 1) * 2 (unknown name 'nlevmlcan' in expression: (nlevmlcan + 1) * 2)

# ----- hoisted execution-part literals (zero-literal rule)
F_1PEM03 = np.float64('1.e-03')  # norman:307
F_2P = np.float64('2.')  # norman:288
I_4 = np.int32(4)  # norman:152; norman:153; norman:171
