"""Machine-generated by recast.transform.jax -- JAX backend (EXPERIMENTAL).

Loop-faithful lax emission from shr_orb_mod_numpy.py. Cannot pass a bit-exact
gate: XLA lowers transcendentals to its own implementations and fuses
multiply-add. The gate is the ULP tier against the validated numpy module --
see recast.verify.tolerance. Do not hand-edit; fix the backend instead.
B-block provenance lives in the numpy module.
"""

import jax
import jax.numpy as jnp
import numpy as np
from jax import lax

from shr_orb_mod_jax_runtime import *  # noqa: F401,F403  (enables x64, _f_* jnp shims)
from shr_orb_mod_constants import *  # noqa: F401,F403
import shr_orb_mod_numpy as _host

# Which device this module will run on. A ULP bound between a GPU and a CPU is
# a different claim from one between two CPUs, and the gate records what the
# module says rather than importing an accelerator to find out.
_DEVICE = str(jax.devices()[0])

import clm_varcon_numpy as _clm_varcon

_SIGNATURES = {'shr_orb_cosz': {'kind': 'function', 'args': [{'name': 'jday', 'dtype': 'float64', 'intent': 'IN', 'optional': False}, {'name': 'lat', 'dtype': 'float64', 'intent': 'IN', 'optional': False}, {'name': 'lon', 'dtype': 'float64', 'intent': 'IN', 'optional': False}, {'name': 'declin', 'dtype': 'float64', 'intent': 'IN', 'optional': False}], 'result': 'shr_orb_cosz', 'result_dtype': 'float64'}, 'shr_orb_decl': {'kind': 'subroutine', 'args': [{'name': 'calday', 'dtype': 'float64', 'intent': 'IN', 'optional': False}, {'name': 'eccen', 'dtype': 'float64', 'intent': 'IN', 'optional': False}, {'name': 'mvelpp', 'dtype': 'float64', 'intent': 'IN', 'optional': False}, {'name': 'lambm0', 'dtype': 'float64', 'intent': 'IN', 'optional': False}, {'name': 'obliqr', 'dtype': 'float64', 'intent': 'IN', 'optional': False}, {'name': 'delta', 'dtype': 'float64', 'intent': 'OUT', 'optional': False}, {'name': 'eccf', 'dtype': 'float64', 'intent': 'OUT', 'optional': False}], 'result': None, 'result_dtype': None}, 'shr_orb_params': {'kind': 'subroutine', 'args': [{'name': 'iyear_ad', 'dtype': 'int32', 'intent': 'IN', 'optional': False}, {'name': 'eccen', 'dtype': 'float64', 'intent': 'OUT', 'optional': False}, {'name': 'obliq', 'dtype': 'float64', 'intent': 'OUT', 'optional': False}, {'name': 'mvelp', 'dtype': 'float64', 'intent': 'OUT', 'optional': False}, {'name': 'obliqr', 'dtype': 'float64', 'intent': 'OUT', 'optional': False}, {'name': 'lambm0', 'dtype': 'float64', 'intent': 'OUT', 'optional': False}, {'name': 'mvelpp', 'dtype': 'float64', 'intent': 'OUT', 'optional': False}], 'result': None, 'result_dtype': None}}


def _shr_orb_cosz_k_impl(jday, lat, lon, declin):
    """L25-L41 function (machine-translated)."""
    shr_orb_cosz = jnp.float64(0.0)
    shr_orb_cosz = jnp.sin(lat) * jnp.sin(declin) - jnp.cos(lat) * jnp.cos(declin) * jnp.cos(jday * F_2P * _clm_varcon.rpi + lon)
    return shr_orb_cosz


_shr_orb_cosz_k = jax.jit(_shr_orb_cosz_k_impl, static_argnums=())


def shr_orb_cosz(jday, lat, lon, declin):
    """Host wrapper: state read from the validated numpy module."""
    return _shr_orb_cosz_k(jday, lat, lon, declin)


def _shr_orb_decl_k_impl(calday, eccen, mvelpp, lambm0, obliqr):
    """L44-L108 subroutine (machine-translated)."""
    delta = jnp.float64(0.0)
    eccf = jnp.float64(0.0)
    dayspy = np.float64('365.')
    ve = np.float64('80.5')
    lambm = jnp.float64(0.0)
    lmm = jnp.float64(0.0)
    lamb = jnp.float64(0.0)
    invrho = jnp.float64(0.0)
    sinl = jnp.float64(0.0)
    lambm = lambm0 + (calday - ve) * F_2P * _clm_varcon.rpi / dayspy
    lmm = lambm - mvelpp
    sinl = jnp.sin(lmm)
    lamb = lambm + eccen * (F_2P * sinl + eccen * (F_1P25 * jnp.sin(F_2P * lmm) + eccen * (F_13P0 / F_12P0 * jnp.sin(F_3P * lmm) - F_0P25 * sinl)))
    invrho = (1.0 + eccen * jnp.cos(lamb - mvelpp)) / (1.0 - eccen * eccen)
    delta = jnp.asin(jnp.sin(obliqr) * jnp.sin(lamb))
    eccf = invrho * invrho
    return (delta, eccf)


_shr_orb_decl_k = jax.jit(_shr_orb_decl_k_impl, static_argnums=())


def shr_orb_decl(calday, eccen, mvelpp, lambm0, obliqr):
    """Host wrapper: state read from the validated numpy module."""
    return _shr_orb_decl_k(calday, eccen, mvelpp, lambm0, obliqr)


def _shr_orb_params_k_impl(iyear_ad):
    """L111-L467 subroutine (machine-translated)."""
    eccen = jnp.float64(0.0)
    obliq = jnp.float64(0.0)
    mvelp = jnp.float64(0.0)
    obliqr = jnp.float64(0.0)
    lambm0 = jnp.float64(0.0)
    mvelpp = jnp.float64(0.0)
    poblen = jnp.int32(47)
    pecclen = jnp.int32(19)
    pmvelen = jnp.int32(78)
    psecdeg = 1.0 / 3600.0
    obamp = jnp.array([-2462.2214466, -857.3232075, -629.3231835, -414.2804924, -311.7632587, 308.9408604, -162.5533601, -116.1077911, 101.1189923, -67.6856209, 24.9079067, 22.5811241, -21.1648355, -15.6549876, 15.3936813, 14.6660938, -11.7273029, 10.2742696, 6.4914588, 5.8539148, -5.4872205, -5.4290191, 5.160957, 5.0786314, -4.0735782, 3.7227167, 3.3971932, -2.8347004, -2.6550721, -2.5717867, -2.4712188, 2.462541, 2.2464112, -2.0755511, -1.9713669, -1.8813061, -1.8468785, 1.8186742, 1.7601888, -1.5428851, 1.4738838, -1.4593669, 1.4192259, -1.181898, 1.1756474, -1.1316126, 1.0896928])
    obrate = jnp.array([31.609974, 32.620504, 24.172203, 31.983787, 44.828336, 30.973257, 43.668246, 32.246691, 30.599444, 42.681324, 43.836462, 47.439436, 63.219948, 64.230478, 1.01053, 7.437771, 55.782177, 0.373813, 13.218362, 62.583231, 63.593761, 76.43831, 45.815258, 8.448301, 56.792707, 49.747842, 12.058272, 75.27822, 65.241008, 64.604291, 1.647247, 7.811584, 12.207832, 63.856665, 56.15599, 77.44884, 6.801054, 62.209418, 20.656133, 48.344406, 55.14546, 69.000539, 11.07135, 74.291298, 11.047742, 0.636717, 12.844549])
    obphas = jnp.array([251.9025, 280.8325, 128.3057, 292.7252, 15.3747, 263.7951, 308.4258, 240.0099, 222.9725, 268.7809, 316.7998, 319.6024, 143.805, 172.7351, 28.93, 123.5968, 20.2082, 40.8226, 123.4722, 155.6977, 184.6277, 267.2772, 55.0196, 152.5268, 49.1382, 204.6609, 56.5233, 200.3284, 201.6651, 213.5577, 17.0374, 164.4194, 94.5422, 131.9124, 61.0309, 296.2073, 135.4894, 114.875, 247.0691, 256.6114, 32.1008, 143.6804, 16.8784, 160.6835, 27.5932, 348.1074, 82.6496])
    ecamp = jnp.array([0.01860798, 0.01627522, -0.0130066, 0.00988829, -0.003367, 0.00333077, -0.002354, 0.00140015, 0.001007, 0.000857, 0.0006499, 0.000599, 0.000378, -0.000337, 0.000276, 0.000182, -0.000174, -0.000124, 1.25e-05])
    ecrate = jnp.array([4.207205, 7.346091, 17.857263, 17.220546, 16.846733, 5.199079, 18.231076, 26.216758, 6.359169, 16.210016, 3.065181, 16.583829, 18.49398, 6.190953, 18.867793, 17.425567, 6.186001, 18.417441, 0.667863])
    ecphas = jnp.array([28.620089, 193.788772, 308.307024, 320.199637, 279.376984, 87.195, 349.129677, 128.443387, 154.14388, 291.269597, 114.860583, 332.092251, 296.414411, 145.76991, 337.237063, 152.092288, 126.839891, 210.667199, 72.108838])
    mvamp = jnp.array([7391.022589, 2555.1526947, 2022.7629188, -1973.6517951, 1240.2321818, 953.8679112, -931.7537108, 872.3795383, 606.3544732, -496.0274038, 456.9608039, 346.946232, -305.8412902, 249.6173246, -199.10272, 191.0560889, -175.2936572, 165.9068833, 161.1285917, 139.7878093, -133.5228399, 117.0673811, 104.6907281, 95.3227476, 86.7824524, 86.0857729, 70.5893698, -69.9719343, -62.5817473, 61.5450059, -57.9364011, 57.1899832, -57.0236109, -54.2119253, 53.2834147, 52.1223575, -49.0059908, -48.3118757, -45.4191685, -42.235792, -34.7971099, 34.4623613, -33.8356643, 33.6689362, -31.2521586, -30.8798701, 28.4640769, -27.1960802, 27.0860736, -26.3437456, 24.725374, 24.6732126, 24.4272733, 24.0127327, 21.7150294, -21.5375347, 18.1148363, -16.9603104, -16.1765215, 15.5567653, 15.4846529, 15.2150632, 14.5047426, -14.3873316, 13.1351419, 12.8776311, 11.9867234, 11.9385578, 11.7030822, 11.6018181, -11.2617293, -10.4664199, 10.433397, -10.2377466, 10.1934446, -10.1280191, 10.0289441, -10.0034259])
    mvrate = jnp.array([31.609974, 32.620504, 24.172203, 0.636717, 31.983787, 3.138886, 30.973257, 44.828336, 0.991874, 0.373813, 43.668246, 32.246691, 30.599444, 2.147012, 10.511172, 42.681324, 13.650058, 0.986922, 9.874455, 13.013341, 0.262904, 0.004952, 1.142024, 63.219948, 0.205021, 2.151964, 64.230478, 43.836462, 47.439436, 1.384343, 7.437771, 18.829299, 9.500642, 0.431696, 1.16009, 55.782177, 12.639528, 1.155138, 0.168216, 1.647247, 10.884985, 5.610937, 12.658184, 1.01053, 1.983748, 14.023871, 0.560178, 1.273434, 12.021467, 62.583231, 63.593761, 76.43831, 4.28091, 13.218362, 17.818769, 8.359495, 56.792707, 8.448301, 1.978796, 8.863925, 0.186365, 8.996212, 6.771027, 45.815258, 12.002811, 75.27822, 65.241008, 18.870667, 22.009553, 64.604291, 11.498094, 0.578834, 9.237738, 49.747842, 2.147012, 1.196895, 2.133898, 0.173168])
    mvphas = jnp.array([251.9025, 280.8325, 128.3057, 348.1074, 292.7252, 165.1686, 263.7951, 15.3747, 58.5749, 40.8226, 308.4258, 240.0099, 222.9725, 106.5937, 114.5182, 268.7809, 279.6869, 39.6448, 126.4108, 291.5795, 307.2848, 18.93, 273.7596, 143.805, 191.8927, 125.5237, 172.7351, 316.7998, 319.6024, 69.7526, 123.5968, 217.6432, 85.5882, 156.2147, 66.9489, 20.2082, 250.7568, 48.0188, 8.3739, 17.0374, 155.3409, 94.1709, 221.112, 28.93, 117.1498, 320.5095, 262.3602, 336.2148, 233.0046, 155.6977, 184.6277, 267.2772, 78.9281, 123.4722, 188.7132, 180.1364, 49.1382, 152.5268, 98.2198, 97.4808, 221.5376, 168.2438, 161.1199, 55.0196, 262.6495, 200.3284, 201.6651, 294.6547, 99.8233, 213.5577, 154.1631, 232.7153, 138.3034, 204.6609, 106.5938, 250.4676, 332.3345, 27.3039])
    degrad = jnp.float64(0.0)
    yb4_1950ad = jnp.float64(0.0)
    i = jnp.int32(0)
    obsum = jnp.float64(0.0)
    cossum = jnp.float64(0.0)
    sinsum = jnp.float64(0.0)
    fvelp = jnp.float64(0.0)
    mvsum = jnp.float64(0.0)
    beta = jnp.float64(0.0)
    years = jnp.float64(0.0)
    eccen2 = jnp.float64(0.0)
    eccen3 = jnp.float64(0.0)
    degrad = _clm_varcon.rpi / F_180P
    yb4_1950ad = F_1950P0 - np.float64(iyear_ad)
    years = -yb4_1950ad
    obsum = jnp.float64(0.0)

    def _body_2(i, _c):
        obsum, = _c

        def _true_1(_c):
            obsum, = _c
            obsum = obsum + obamp[i - 1] * psecdeg * jnp.cos((obrate[i - 1] * psecdeg * years + obphas[i - 1]) * degrad)
            return (obsum,)

        def _false_1(_c):
            obsum, = _c
            return (obsum,)
        obsum, = lax.cond(i < poblen + 1, _true_1, _false_1, (obsum,))
        return (obsum,)
    obsum, = lax.fori_loop(1, obamp.shape[0] + 1, _body_2, (obsum,))
    obliq = F_23P320556 + obsum
    cossum = jnp.float64(0.0)

    def _body_4(i, _c):
        cossum, = _c

        def _true_3(_c):
            cossum, = _c
            cossum = cossum + ecamp[i - 1] * jnp.cos((ecrate[i - 1] * psecdeg * years + ecphas[i - 1]) * degrad)
            return (cossum,)

        def _false_3(_c):
            cossum, = _c
            return (cossum,)
        cossum, = lax.cond(i < pecclen + 1, _true_3, _false_3, (cossum,))
        return (cossum,)
    cossum, = lax.fori_loop(1, ecamp.shape[0] + 1, _body_4, (cossum,))
    sinsum = jnp.float64(0.0)

    def _body_6(i, _c):
        sinsum, = _c

        def _true_5(_c):
            sinsum, = _c
            sinsum = sinsum + ecamp[i - 1] * jnp.sin((ecrate[i - 1] * psecdeg * years + ecphas[i - 1]) * degrad)
            return (sinsum,)

        def _false_5(_c):
            sinsum, = _c
            return (sinsum,)
        sinsum, = lax.cond(i < pecclen + 1, _true_5, _false_5, (sinsum,))
        return (sinsum,)
    sinsum, = lax.fori_loop(1, ecamp.shape[0] + 1, _body_6, (sinsum,))
    eccen2 = cossum * cossum + sinsum * sinsum
    eccen = jnp.sqrt(eccen2)
    eccen3 = eccen2 * eccen

    def _true_13(_c):
        fvelp, = _c

        def _true_9(_c):
            fvelp, = _c
            fvelp = jnp.float64(0.0)
            return (fvelp,)

        def _false_9(_c):
            fvelp, = _c

            def _true_8(_c):
                fvelp, = _c
                fvelp = F_1P5 * _clm_varcon.rpi
                return (fvelp,)

            def _false_8(_c):
                fvelp, = _c

                def _true_7(_c):
                    fvelp, = _c
                    fvelp = 0.5 * _clm_varcon.rpi
                    return (fvelp,)

                def _false_7(_c):
                    fvelp, = _c
                    return (fvelp,)
                fvelp, = lax.cond(sinsum > 0.0, _true_7, _false_7, (fvelp,))
                return (fvelp,)
            fvelp, = lax.cond(sinsum < 0.0, _true_8, _false_8, (fvelp,))
            return (fvelp,)
        fvelp, = lax.cond(sinsum == 0.0, _true_9, _false_9, (fvelp,))
        return (fvelp,)

    def _false_13(_c):
        fvelp, = _c

        def _true_12(_c):
            fvelp, = _c
            fvelp = jnp.atan(sinsum / cossum) + _clm_varcon.rpi
            return (fvelp,)

        def _false_12(_c):
            fvelp, = _c

            def _true_11(_c):
                fvelp, = _c

                def _true_10(_c):
                    fvelp, = _c
                    fvelp = jnp.atan(sinsum / cossum) + F_2P0 * _clm_varcon.rpi
                    return (fvelp,)

                def _false_10(_c):
                    fvelp, = _c
                    fvelp = jnp.atan(sinsum / cossum)
                    return (fvelp,)
                fvelp, = lax.cond(sinsum < 0.0, _true_10, _false_10, (fvelp,))
                return (fvelp,)

            def _false_11(_c):
                fvelp, = _c
                return (fvelp,)
            fvelp, = lax.cond(cossum > 0.0, _true_11, _false_11, (fvelp,))
            return (fvelp,)
        fvelp, = lax.cond(cossum < 0.0, _true_12, _false_12, (fvelp,))
        return (fvelp,)
    fvelp, = lax.cond(abs(cossum) <= F_1P0EM8, _true_13, _false_13, (fvelp,))
    mvsum = jnp.float64(0.0)

    def _body_15(i, _c):
        mvsum, = _c

        def _true_14(_c):
            mvsum, = _c
            mvsum = mvsum + mvamp[i - 1] * psecdeg * jnp.sin((mvrate[i - 1] * psecdeg * years + mvphas[i - 1]) * degrad)
            return (mvsum,)

        def _false_14(_c):
            mvsum, = _c
            return (mvsum,)
        mvsum, = lax.cond(i < pmvelen + 1, _true_14, _false_14, (mvsum,))
        return (mvsum,)
    mvsum, = lax.fori_loop(1, mvamp.shape[0] + 1, _body_15, (mvsum,))
    mvelp = fvelp / degrad + F_50P439273 * psecdeg * years + F_3P392506 + mvsum
    _done_1 = False

    def _wcond_1(_c):
        mvelp, _done_1 = _c
        return jnp.logical_and(jnp.logical_not(_done_1), mvelp < 0.0)

    def _wbody_1(_c):
        mvelp, _done_1 = _c
        mvelp = mvelp + F_360P0
        return (mvelp, _done_1)
    mvelp, _done_1 = lax.while_loop(_wcond_1, _wbody_1, (mvelp, _done_1))
    _done_2 = False

    def _wcond_2(_c):
        mvelp, _done_2 = _c
        return jnp.logical_and(jnp.logical_not(_done_2), mvelp >= F_360P0)

    def _wbody_2(_c):
        mvelp, _done_2 = _c
        mvelp = mvelp - F_360P0
        return (mvelp, _done_2)
    mvelp, _done_2 = lax.while_loop(_wcond_2, _wbody_2, (mvelp, _done_2))
    obliqr = obliq * degrad
    mvelpp = (mvelp + F_180P) * degrad
    beta = jnp.sqrt(1.0 - eccen2)
    lambm0 = F_2P * ((0.5 * eccen + F_P125 * eccen3) * (1.0 + beta) * jnp.sin(mvelpp) - F_P250 * eccen2 * (0.5 + beta) * jnp.sin(F_2P * mvelpp) + F_P125 * eccen3 * (1.0 / F_3P + beta) * jnp.sin(F_3P * mvelpp))
    return (eccen, obliq, mvelp, obliqr, lambm0, mvelpp)


_shr_orb_params_k = jax.jit(_shr_orb_params_k_impl, static_argnums=(0,))


def shr_orb_params(iyear_ad):
    """Host wrapper: state read from the validated numpy module."""
    return _shr_orb_params_k(iyear_ad)


_JAX_KERNELS = ['shr_orb_cosz', 'shr_orb_decl', 'shr_orb_params']
