"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module surfacealbedotype; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

NUMRAD = 2  # clm_varpar.f90:20
ISPVAL = (-9999)  # clm_varcon.f90:45
SPVAL = np.float64('1.e36')  # clm_varcon.f90:44
