"""Machine-generated by recast — DO NOT EDIT."""
# source: TemperatureType.f90 (module temperaturetype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
