"""Machine-generated by recast — DO NOT EDIT."""
# source: WaterFluxBulkType.f90 (module waterfluxbulktype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
