"""Machine-generated by recast — DO NOT EDIT."""
# source: MLpftconMod.f90 (module mlpftconmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P0001 = np.float64('0.0001')  # initread:261
F_0P002 = np.float64('0.002')  # initread:241
F_0P01 = np.float64('0.01')  # initread:248; initread:250
F_0P04 = np.float64('0.04')  # initread:249
F_0P29EM03 = np.float64('0.29e-03')  # initread:234
F_0P31E06 = np.float64('0.31e06')  # initread:235
F_0P98 = np.float64('0.98')  # initread:293
F_100P7 = np.float64('100.7')  # initread:208; initread:209
F_125P = np.float64('125.')  # initread:305
F_14P = np.float64('14.')  # initread:308
F_1500P = np.float64('1500.')  # initread:224
F_1P60 = np.float64('1.60')  # initread:314
F_1P62 = np.float64('1.62')  # initread:276
F_2500P = np.float64('2500.')  # initread:217
F_25P = np.float64('25.')  # initread:236
F_2P22 = np.float64('2.22')  # initread:274
F_2P3 = np.float64('2.3')  # initread:283
F_2P35 = np.float64('2.35')  # initread:263; initread:264; initread:265
F_375P = np.float64('375.')  # initread:307
F_39P1 = np.float64('39.1')  # initread:196
F_40P = np.float64('40.')  # initread:288
F_40P0 = np.float64('40.0')  # initread:315
F_41P0 = np.float64('41.0')  # initread:197; initread:199
F_4P = np.float64('4.')  # initread:214; initread:253
F_4P12 = np.float64('4.12')  # initread:266; initread:267
F_4P45 = np.float64('4.45')  # initread:268; initread:269; initread:270
F_4P70 = np.float64('4.70')  # initread:271; initread:272; initread:273
F_500P = np.float64('500.')  # initread:218; initread:225
F_51P6 = np.float64('51.6')  # initread:207
F_54P0 = np.float64('54.0')  # initread:203; initread:204
F_57P7 = np.float64('57.7')  # initread:200; initread:201
F_5P25 = np.float64('5.25')  # initread:275
F_5P79 = np.float64('5.79')  # initread:277; initread:278
F_61P4 = np.float64('61.4')  # initread:198
F_61P7 = np.float64('61.7')  # initread:202
F_62P5 = np.float64('62.5')  # initread:194; initread:195
F_750P = np.float64('750.')  # initread:223; initread:226
F_78P2 = np.float64('78.2')  # initread:205; initread:206
F_7P = np.float64('7.')  # initread:306
F_999P = np.float64('999.')  # initread:193; initread:213; initread:216; initread:222; initread:230; initread:231; initread:232; initread:240; initread:245; initread:246; initread:258; initread:259; initread:282; initread:287; initread:292; initread:297
F_9P = np.float64('9.')  # initread:252; initread:254
I_10 = np.int32(10)  # initread:203; initread:272
I_11 = np.int32(11)  # initread:204; initread:217; initread:273
I_12 = np.int32(12)  # initread:205; initread:218; initread:274
I_13 = np.int32(13)  # initread:206; initread:248; initread:252; initread:275
I_14 = np.int32(14)  # initread:207; initread:249; initread:253; initread:276
I_15 = np.int32(15)  # initread:208; initread:250; initread:254; initread:277
I_16 = np.int32(16)  # initread:209; initread:214; initread:218; initread:226; initread:234; initread:235; initread:236; initread:241; initread:250; initread:254; initread:261; initread:278; initread:283; initread:288; initread:293; initread:298
I_3 = np.int32(3)  # initread:196; initread:224; initread:265
I_4 = np.int32(4)  # initread:197; initread:225; initread:266
I_5 = np.int32(5)  # initread:198; initread:226; initread:267
I_6 = np.int32(6)  # initread:199; initread:268
I_7 = np.int32(7)  # initread:200; initread:269; initread:305; initread:306; initread:307; initread:308; initread:314; initread:315
I_8 = np.int32(8)  # initread:201; initread:270
I_9 = np.int32(9)  # initread:202; initread:271
