"""Machine-generated by recast.transform.jax -- JAX backend (EXPERIMENTAL).

Loop-faithful lax emission from clm_varpar_numpy.py. Cannot pass a bit-exact
gate: XLA lowers transcendentals to its own implementations and fuses
multiply-add. The gate is the ULP tier against the validated numpy module --
see recast.verify.tolerance. Do not hand-edit; fix the backend instead.
B-block provenance lives in the numpy module.
"""

import jax
import jax.numpy as jnp
import numpy as np
from jax import lax

from clm_varpar_jax_runtime import *  # noqa: F401,F403  (enables x64, _f_* jnp shims)
from clm_varpar_constants import *  # noqa: F401,F403
import clm_varpar_numpy as _host

# Which device this module will run on. A ULP bound between a GPU and a CPU is
# a different claim from one between two CPUs, and the gate records what the
# module says rather than importing an accelerator to find out.
_DEVICE = str(jax.devices()[0])

import clmsoiloptionmod_numpy as _clm

_SIGNATURES = {'clm_varpar_init': {'kind': 'subroutine', 'public': True, 'args': [], 'result': None, 'result_dtype': None}}


def _clm_varpar_init_k_impl(nlevgrnd, nlevsno, nlevsoi):
    """L31-L52 subroutine (machine-translated)."""

    def _true_2(_c):
        nlevsno, nlevsoi, nlevgrnd = _c
        nlevsno = I_12
        nlevsoi = I_20
        nlevgrnd = nlevsoi + I_5
        return (nlevsno, nlevsoi, nlevgrnd)

    def _false_2(_c):
        nlevsno, nlevsoi, nlevgrnd = _c

        def _true_1(_c):
            nlevsno, nlevsoi, nlevgrnd = _c
            nlevsno = I_5
            nlevsoi = I_10
            nlevgrnd = I_15
            return (nlevsno, nlevsoi, nlevgrnd)

        def _false_1(_c):
            nlevsno, nlevsoi, nlevgrnd = _c
            return (nlevsno, nlevsoi, nlevgrnd)
        nlevsno, nlevsoi, nlevgrnd = lax.cond(_fstr_eq(_clm.clm_phys, 'CLM4_5'), _true_1, _false_1, (nlevsno, nlevsoi, nlevgrnd))
        return (nlevsno, nlevsoi, nlevgrnd)
    nlevsno, nlevsoi, nlevgrnd = lax.cond(_fstr_eq(_clm.clm_phys, 'CLM5_0'), _true_2, _false_2, (nlevsno, nlevsoi, nlevgrnd))
    return (nlevgrnd, nlevsno, nlevsoi)


_clm_varpar_init_k = jax.jit(_clm_varpar_init_k_impl, static_argnums=())


def clm_varpar_init():
    """Host wrapper: state threads through; writes land on the host."""
    _res = _clm_varpar_init_k(_host.nlevgrnd, _host.nlevsno, _host.nlevsoi)
    _host.nlevgrnd = _res[0]
    _host.nlevsno = _res[1]
    _host.nlevsoi = _res[2]
    return None


_JAX_KERNELS = ['clm_varpar_init']
