"""Machine-generated by recast — DO NOT EDIT."""
# source: MLCanopyWaterMod.f90 (module mlcanopywatermod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
