"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlfluxprofilesolutionmod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

ISUN = 1  # MLclm_varpar.f90:20
ISHA = 2  # MLclm_varpar.f90:21
NLEVMLCAN = 100  # MLclm_varpar.f90:18
NLEAF = 2  # MLclm_varpar.f90:19
