"""Machine-generated by recast — DO NOT EDIT."""
# source: MLFluxProfileSolutionMod.f90 (module mlfluxprofilesolutionmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P001 = np.float64('0.001')  # errorcheck01:614; errorcheck01:618; errorcheck01:622; errorcheck01:638; errorcheck01:642; errorcheck01:646; errorcheck02:706; errorcheck02:719; errorcheck02:729; errorcheck02:744; errorcheck02:756; errorcheck02:763
F_100P = np.float64('100.')  # wellmixed:884
F_10P = np.float64('10.')  # wellmixed:895
F_1PEM06 = np.float64('1.e-06')  # errorcheck01:626; errorcheck01:630; errorcheck01:650; errorcheck01:654
F_2P = np.float64('2.')  # implicitfluxprofilesolution:284
F_42P3 = np.float64('42.3')  # wellmixed:884; wellmixed:895
