"""Machine-generated by recast — DO NOT EDIT."""
# source: atm2lndType.f90 (module atm2lndtype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
