"""Machine-generated by recast — DO NOT EDIT.
Use-imported constants for module mlwatervapormod; same parsed
expressions as the Fortran stand-in (bit parity by construction)."""

import numpy as np

TFRZ = np.float64('273.15')  # clm_varcon.f90:21
HVAP = np.float64('2.5010e6')  # clm_varcon.f90:31
HSUB = np.float64('2.8347e6')  # clm_varcon.f90:32
MMH2O = (np.float64('18.02') * np.float64('1.e-03'))  # MLclm_varcon.f90:21
