"""Machine-generated by recast — DO NOT EDIT."""
# source: MLPlantHydraulicsMod.f90 (module mlplanthydraulicsmod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_1000P = np.float64('1000.')  # leafwaterpotential:320; soilresistance:181
F_1PEM03 = np.float64('1.e-03')  # soilresistance:180; soilresistance:182
F_1PEM06 = np.float64('1.e-06')  # leafwaterpotential:304; soilresistance:155
F_1PEM10 = np.float64('1.e-10')  # soilresistance:187
F_2P = np.float64('2.')  # soilresistance:199
