"""Machine-generated by recast — DO NOT EDIT."""
# source: MLCanopyFluxesType.f90 (module mlcanopyfluxestype)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P1 = np.float64('0.1')  # initcold:765; initcold:766
