"""Machine-generated by recast — DO NOT EDIT."""
# source: MLLeafHeatCapacityMod.f90 (module mlleafheatcapacitymod)

import numpy as np

# ----- module-level parameters

# ----- subprogram-local parameters

# ----- hoisted execution-part literals (zero-literal rule)
F_0P001 = np.float64('0.001')  # leafheatcapacity:73
